rackerlabs/rackspace-how-to

- content/cloud-big-data/detailed-permissions-matrix-for-cloud-big-data-v2.md
- Removed a name html tag that caused heading not to render.
- Put link to API documentation in a note.
- Removed bookmark reference to terminology section.
> Syntax fixes.

- content/general/legal.md
Removed Knowledge Center throughout article, and replaced with How To.
> Remove Knowledge Center in article

- content/cloud-dns/create-a-dkim-txt-record.md
- content/cloud-dns/create-a-reverse-dns-record-0.md
- content/cloud-dns/create-an-spf-txt-record.md
- content/cloud-networks/create-an-isolated-cloud-network-and-attach-it-to-a-server.md
- content/cloud-servers/connecting-to-linux-from-mac-os-x-by-using-terminal.md
- content/cloud-servers/connecting-to-linux-from-windows-by-using-putty.md
- content/cloud-servers/create-a-cloud-server.md
- content/cloud-servers/create-a-csr-in-the-cloud-control-panel.md
- content/cloud-servers/create-an-image-of-a-general-purpose-v1-cloud-server.md
- content/cloud-servers/create-an-image-of-a-server-and-restore-a-server-from-a-saved-image.md
- content/cloud-servers/create-an-inbound-port-allow-rule-for-windows-firewall-2008.md
- content/cloud-servers/create-onmetal-cloud-servers.md
- content/cloud-servers/creating-a-general-purpose-cloud-server.md
- content/cloud-servers/creating-an-image-backup-cloning.md
part 9? of the servers content audit: moved networks and DNS articles to their appropriate home, fixed a lot of header levels, formatting for bulleted and numbered lists, code, images, and links.
> Servers content audit

- content/cloud-block-storage/attach-a-cloud-block-storage-volume-to-an-onmetal-server-through-the-cloud-control-panel.md
- content/cloud-block-storage/attach-a-cloud-block-storage-volume-to-an-onmetal-server.md
FYI, these back ticks break the preparer.
When the how-to editor is in place, this won't be an issue... but when editing directly in github, please watch that your editor isn't "helping" too much.  Thanks!
> fix backticks added to front matter

- content/cloud-load-balancers/load-balancing-internal-ips-in-the-same-region.md
Replace "Why is this important?" header with "Use regions and the Rackspace network to manage bandwidth charges
> Fix heading levels

- content/cloud-networks/configuring-interface-based-firewall-on-the-vyatta-network-appliance.md
Issues were arising from standard text and cod examples within the ordered list of steps. Enclosed numbers in paren to adapt.
> Fix markdown numbering.

- content/cloud-dns/about-ttl-best-practices.md
- content/cloud-servers/about-volume-types.md
- content/cloud-servers/apache-configuration-on-ubuntu.md
@ReneeRendon 
These are the three articles linked to from the CP that should have been migrated:
Node 450 - Apache configuration on Ubuntu
Node 1518 - About TTL best practices
Node 2007 - About volume types
Review these, please, and let me know if you see anything strange. Otherwise, feel free to merge.
> Migrate cp articles

- content/cloud-servers/rackspace-cloud-essentials-rescue-mode-on-windows-cloud-servers-behaviors.md
This is the "Rackspace Cloud Essentials - Rescue Mode on Windows Cloud Servers behaviors" article linked to from the Control Panel.
It's missing one image, but I've added it to the KC migration issue log. I've left a note where the image should be. It won't display when rendered into HTML, so this would be safe to merge as-is.
@ReneeRendon want to take a look?
> add article linked to from cp that should have been migrated

- content/cloud-servers/basic-settings-in-the-postfix-maincf-file.md
The published version on the KC doesn't have this link, so I'm not sure how it squeaked through. I've removed it.
> removing link to unmigrated article

- content/cloud-images/cloud-images-faq.md
Took out the links that shouldn't have been links in the Images FAQ and fixed the formatting of links and images.
> fix weird links in rbac section and link formatting

- content/cloud-sites/rackspace-cloud-sites-essentials-phpmyadmin-database-management-interface.md
Two images were missing the opening parentheses causing them to not be displayed.
> Fix broken image links

- content/cloud-sites/modify-your-hosts-file.md
From Trello card (https://trello.com/c/63ofSXvP) for this change:
The instructions in the section "Mac OS X 10.6 through 10.8” are also valid for 10.9 and 10.10.
As such, the instructions should be inclusive of those versions.
Joe Ashcraft
// Managed Cloud, Linux
> Change occurrences of 10.8 to 10.10

- content/cloud-sites/como-modificar-mi-archivo-de-hosts.md
- content/cloud-sites/como-modifico-meus-arquivos-de-hosts.md
Very similar changes #442 and #444.
I've updated the OSX version for which these instructions are valid, and fixed a the commands for Linux, OSX which included extra spaces.
> Joeashcraft hosts files 1

- content/cloud-servers/first-gen-to-next-gen-cloud-servers-migration-pre-checks.md
- content/cloud-servers/migrating-a-linux-server-from-the-command-line-1.md
Fixing a link to go to the proper migration article, per email request.
> Rsync link fix

- CONTRIBUTING.md
Remove part of the instructions that say that the contributor may be asked to merge the PR. Contributors should not merge their own PRs.
> Remove "merge" phrase.

- content/cloud-databases/access-slow-query-and-general-logs-for-cloud-databases.md
expire_logs_days only refers to the retention of binlogs, so it's not being used correctly in this How-To. I've removed all references.
> Remove all expire_logs_days references in slow query log how-to

- content/cloud-big-data/cloud-big-data-platform-provisioning-and-pricing.md
- content/cloud-databases/cloud-databases-faq.md
- content/cloud-databases/cloud-databases.md
- content/cloud-databases/monitoring-cloud-databases-in-the-cloud-control-panel.md
- content/cloud-files/cloud-files.md
- content/cloud-files/mounting-rackspace-cloud-files-to-linux-using-cloudfuse.md
- content/cloud-files/streaming-cloud-files-with-jw-player.md
- content/cloud-files/use-swiftly-to-upload-an-image.md
- content/cloud-images/identifying-rackspace-standard-images.md
- content/cloud-images/transferring-images-between-regions-of-the-rackspace-open-cloud.md
- content/cloud-load-balancers/content-caching-for-cloud-load-balancers.md
- content/cloud-monitoring/alarm-language-generic-thresholds-made-easy.md
- content/cloud-monitoring/getting-started-with-rackspace-monitoring-cli.md
- content/cloud-monitoring/rackspace-monitoring-checks-and-alarms.md
- content/cloud-queues/cloud-queues-curl-cookbook.md
- content/cloud-queues/tips-for-monitoring-your-queues-in-cloud-queues.md
- content/cloud-servers/boot-a-server-from-a-cloud-block-storage-volume.md
- content/cloud-servers/detailed-permissions-matrix-for-dns.md
- content/cloud-servers/faq-for-seamless-sign-on-between-myrackspace-and-the-cloud-control-panel.md
- content/cloud-servers/getting-started-with-cloud-servers.md
- content/cloud-servers/manage-ssh-key-pairs-for-cloud-servers-with-python-novaclient.md
- content/cloud-servers/using-python-novaclient-to-manage-scheduled-images.md
- content/general/known-issues-and-suggested-workarounds-role-based-access-control-rbac.md
- content/managed-operations/cloud-servers-with-managed-operations-support-for-linux.md
- content/managed-operations/managed-operations-faq.md
- content/rackconnect/getting-started-with-the-rackconnect-v30-api.md
- content/rackconnect/rackconnect-auto-nat-feature.md
- content/rackconnect/rackconnect-v30-cloud-server-image-compatibility.md
- content/rackspace-auto-scale/cloud-bursting-using-auto-scale-rackconnect-and-f5-load-balancers.md
Change docs.rackspace references to point to DRC. 
Outstanding docs.rackspace references include: Cloud Feeds, RPC, VMWare, First Gen Cloud Server, and one code sample.
> Update docs links#411

- content/rackspace-metrics/use-annotation-metrics.md
Looks like the metadata was copy/pasted from a raw git view, so it had those little plus signs in front of each line, preventing the metadata from being parsed properly.
Fixes #555
> remove plus signs from metadata

- content/exchange/public-folders-availability-for-hosted-exchange-2013.md
fixes #401 
As Rose pointed out, there was some unnecessary background information about 2014 updates to Exchange 2013. After reading through it, I thought it worked just fine to take it out completely.
> remove outdated intro

- content/cloud-big-data/cloud-big-data.md
- content/cloud-big-data/manage-cluster-acls-with-iptables.md
Adds a brief article explaining how to inject iptables rules into
the cluster so the user can open ports up to public access if they
require it.
> Add article about managing ACLs in Cloud Big Data clusters

- content/rackspace-cdn/create-a-rackspace-cdn-service.md
This is a change to move away from specifics on the SSL Certificate Authority, as we will be adding more CAs to the list, rather than just GeoTrust.
-Brian Metzler@Rack
> Update to change the Specific GeoTrust to Generic

- content/cloud-backup/best-practices-for-cloud-backup.md
- content/cloud-backup/rackspace-cloud-backup-create-a-backup.md
- content/cloud-backup/rackspace-cloud-backup-overview.md
If a customer believes that CBU will follow symlinks and backup files that are pointed to by the symlinks, they will likely never know that those files are not getting backed up until much too late, when they want to restore one of those files. We need to do due diligence to make sure customers know symlinks are, by design, not followed during CBU backup operations.
> Customer warning: CBU doesn't follow symlinks.

- content/cloud-dns/managed-dns-faq.md
We had additional space between bracket and paran in the links.
> Fix links.

- content/cloud-databases/high-availability-for-cloud-databases.md
- The bullet stating that commands for resizes/configurations/backups must be directed to the HA ID was unclear. Fixed that
- Added a link to the new HA in the control panel article I wrote.
> Small text modifications in Limitations section

- content/cloud-dns/create-a-reverse-dns-record.md
- content/cloud-files/getting-started-with-cloud-files-and-cdn.md
- content/cloud-files/protect-your-cloud-files-cdn-bill-from-unexpected-usage.md
- content/cloud-images/creating-an-ubuntu-1310-image-for-the-rackspace-open-cloud.md
- content/cloud-servers/configuring-basic-security.md
- content/cloud-sites/information-for-mysql-users-mariadb-100.md
- content/cloud-sites/information-for-new-php-56-apache-version.md
- content/exchange/adding-microsoft-exchange-mailboxes.md
- content/rackconnect/rackconnect-release-notes.md
- content/rackspace-email-archiving/set-access-rules-for-archive-end-users.md
- content/rackspace-email/cloud-office-control-panel-0.md
- content/rackspace-email/spam-preferences-safe-lists-and-black-list-in-rackspace-email.md
- content/rackspace-monitoring/alarm-language-generic-thresholds-made-easy.md
This removes the trailing `-0` suffixes that were still in the `permalink` field of several articles.
> remove -0 suffixes from all permalink fields

- .gitignore
- content/cloud-databases/managing-cloud-databases-ha-groups-in-the-cloud-control-panel.md
I've tracked down the "missing assets" problem that's broken the build for the past few days. I've verified locally so this _should_ fix it - we'll know if I get a preview link from Strider.
Like I discovered on #692, there's a bug in the way that Strider pull request builds work right now that's preventing pull requests from getting the red "X" when their builds are failing. Even if a pull request doesn't build at all, the _branch_ build that's created by pushing new branches to this repository will mark the commit as "successful" even though it didn't do anything.
I'll :wrench: to get that fixed. In the meantime, though, getting a preview link (and actually watching the build on Strider) is a more reliable way of knowing that a pull request's changes are healthy.
> Fix images in that one Cloud Databases article

- content/cloud-databases/importing-data-into-cloud-databases.md
Cloud Databases support is able to help and provide guidance on imports, so recommending that customers should touch base with support before doing a large or important import.
> Add language about leveraging support for large imports

- content/cloud-databases/using-ssl-with-your-cloud-database-instance.md
Cloud Databases created after March 1 2016 will require a new CA cert for SSL. This is linking to the new cert.
This one is fairly urgent. Can we push through quickly.
> Updating the SSL doc to point to the new CA cert

- content/cloud-databases/cloud-databases-faq.md
We're adding some new features to Cloud Databases on Apr. 19. I'm updating the documentation for those features, which are:
- Adding MySQL 5.7, Percona 5.7, and MariaDB 10.1
- Raising the maximum volume size to 1TB
- Added a note about HA pricing
> Adding new versions and new volume size

- content/cloud-databases/choosing-the-right-database-with-rackspace-cloud-databases.md
We'll be launching new versions of MySQL on Apr. 19, so getting the How-To docs ready. The new versions are:
- MySQL 5.7
- Percona 5.7
- MariaDB 10.1
> Adding new versions to choosing the right DB article

- content/rackspace-email/upgrade-email-hosting-cloud-office-control-panel.md
Remove control panel links to avoid customer confusion. This article applies to admins who should have some experience with in the cp. Providing links for SA3 and Core accounts can lead to confusion because there is no clear way to explain to the customer which billing system their account may exist in.
> Remove Control Panel Links

- content/cloud-servers/first-gen-to-next-gen-cloud-servers-migration-pre-checks.md
Updated lines 105-108 to reflect that the tools install does require root access.  Please feel free to make changes to make this flow better if needed.
> Tools install needs root perms

- content/cloud-backup/cloud-backup-troubleshooting.md
A few linux admins have noted that the log location should be changed to `/var/log/driveclient.log`. The camel case won't work.
> fixed case on linux log location

- content/cloud-servers/managing-your-server-resizing-standard-and-general-purpose-servers.md
Due to the local disk on the standard servers increasing with resources, these servers can not be resized down.
> Standard servers can only be resized up

- scripts/build-sitemap.sh
sed on mac os x functions a little differently than it does on linux.
this change should make it run properly on os x.
> change build-sitemap.sh to make it osx friendly

- content/cloud-sites/update-an-existing-ssl-certificate.md
Updated some text to remove mention of wild card and/or EV certs not being supported. Brings it in-line with the article for configuring SSL on Cloud Sites
> Remove wildcard/EV certs not being supported

- content/cloud-servers/checking-linux-file-permissions-with-ls.md
Updated wording for df -h to reflect that this is a separate program that also supports the -h flag but does so for usage of the whole drive.
> Changed wording around df -h

- content/cloud-servers/installing-active-directory-domain-services-on-windows-server-2008-r2-enterprise-64-bit.md
- content/cloud-servers/installing-active-directory-on-windows-server-2012.md
- Fixes #1089 Add links between AD Installation articles: 
Install Active Directory on Windows Server 2012
Install Active Directory Domain Services on Windows Server 2008 R2 Enterprise 64-bit
> Add links between AD installation articles.

- content/cloud-backup/generating-your-encrypted-key-in-cloud-backup.md
a redirect was implemented in nexus-control for the title change, but the permalink wasn't changed in the metadata. Changing now to make the article clickable again.
> fix permalink

- content/cloud-servers/rackspace-cloud-essentials-centos-configuring-a-user-in-vsftpd.md
Added space after audit_date to correct metadata which allows page to display correctly.
> Add space after audit_date to correct metadata

- content/cloud-sites/file-permissions-on-cloud-sites.md
Removed reference to CGI, as Cloud Sites has not allowed CGI use for 2 years.
Added link to .NET impersonation article rather than simply suggesting contacting support for help.
Added the mention of what defaults are in Cloud Sites to the table and marked them with italics for readability.
> Updates for current Cloud sites

- content/cloud-networks/cloud-networks-faq.md
I viewed this topic when editing a new article about IP addresses. I noticed that the new "IP" section did not have a horizontal line above it, so I added one. I also removed the hyphen from the article title (not recommended), and removed the intro sentence from the new section (not needed).
> add horizontal line and make minor edits

- content/cloud-databases/database-replication-with-cloud-databases.md
- Adjusted replication and slave thread alerts to be critical rather than Warning
- Changed the logic to be a little more exclusive on the slave thread alerts
- Added a warning threshold on the seconds behind master alert
> Tweaking alert examples in replication page

- content/cloud-databases/choosing-the-right-database-with-rackspace-cloud-databases.md
Fixes #1305 
MySQL 5.7 isn't an option yet in the Control Panel for Cloud Databases, so removing it from the list of supported databases in Choosing the right database with Rackspace Cloud Databases.
> remove mysql v 5.7

- content/cloud-networks/removing-networks-from-a-cloud-server.md
I have added a line into the Limitation section to explicitly state that you are unable to remove the PublicNet and ServiceNet interfaces from a Cloud Server within a Managed Operations account.
> Updated the limitations to include MO restriction

- content/cloud-servers/migrating-a-linux-server-from-the-command-line.md
Fixes #1321 
The link I'm removing here points to an unmigrated article that may end up being reposted in Community. We can always link to it again if it finds a new home.
> delete link to unmigrated article

- content/cloud-servers/about-cloud-server-images.md
Fixes #1333 
Adding the inability to create images of boot from volume servers to the list of limitations.
> add limitation about boot from volume servers

- README.md
Hi y'all,
Can you please scrub your public docs from having private, protected
URLS listed?
https://github.com/rackerlabs/rackspace-how-to/blob/master/README.md
We should not be linking to internal tools like one.rackspace.com, this
is an information leak about internal business processes and design.
This information can possibly be used by a bad actor to map out what's
behind our firewall perimeter.
thx!
-te
-- 
Troy Engel
GNU/Linux Systems Engineer
> Remove internal link

- content/cloud-networks/rackconnect-v20-with-cloud-networks-faq.md
- Fixes issue #1340 
Text indicating code and diagram examples removed per SME suggestion.
> Remove examples from old RackConnect 2.0 article

- content/cloud-block-storage/cloud-block-storage-faq.md
- content/cloud-block-storage/index.md
- content/cloud-block-storage/prepare-your-cloud-block-storage-volume.md
- content/cloud-servers/cloud-servers-faq.md
- content/cloud-servers/permissions-matrix-for-next-generation-cloud-servers.md
- content/cloud-servers/speed-up-rsync-when-migrating-a-linux-server-from-the-command-line.md
- content/managed-operations/windows-server-2012-r2-with-managed-operations-support.md
- content/rackconnect/features-introduced-in-rackconnect-v20.md
- content/rackconnect/how-to-programmatically-determine-the-rackconnect-v20-automation-status-of-your-cloud.md
- content/rackconnect/rackconnect-10-post-upgrade-faq.md
- content/rackconnect/rackconnect-faq.md
- content/rackconnect/rackconnect-power-users-guide.md
- content/rackconnect/rackconnect-release-notes.md
- content/rackconnect/rackconnect-v30-cloud-server-image-compatibility.md
- content/rackconnect/rackconnect-v30-compatibility.md
- content/rackconnect/the-rackconnect-v20-api.md
This round removes "next-generation" with hyphens.
> Remove next-gen from articles

- content/exchange/manually-configure-android-devices-for-email-hosted-on-exchange-2013.md
Forgot to add the `audit_date` after finishing the full audit for "Manually configure Android devices for email hosted on Exchange 2013"
> add audit date for completed full audit

- content/exchange/public-folder-permissions-for-exchange.md
Found another article missing the `permalink` field in the metadata
> add permalink to metadata

- content/cloud-big-data/detailed-permissions-matrix-for-cloud-big-data.md
This matrix looked messed up in the repo, yet displays properly online. Once we merge it, we need to double check that it still displays properly on the site.
> Correct heading style for terminology section

- content/general/comparison-of-dedicated-and-cloud-hosting.md
By referring to the support matrix article we will avoid content get out of date in the future.
> removed content duplication

- content/rackspace-intelligence/rackspace-intelligence-faq.md
The current link to the monitoring api is gone, so you get a 404. I've updated this to include the link to the current monitoring api page.
> Change link to monitoring api

- CONTRIBUTING.md
For our external contributors who copy and paste metadata.
> Delete spaces in permalink example.

- content/rackspace-monitoring/troubleshooting-alarms.md
- Fixes issue #1536 
- Add links for "Monitoring status codes" and "Checks and Alarms"
- Replace all instances of "alarm" with "alert"
- Add further explanation for bad ping responses
- Add link to "common network troubleshooting tools" for ping and traceroute.
Before merging, the article needs to be renamed to reflect new title. A redirect also needs to be added.
> Full audit for Troubleshooting Alerts

- content/rpc-openstack/index.md
On the RPC-OpenStack intro page, the link to the RPC documentation directed back to the same intro page, so updating to point to the docs on developer instead.
> update link to rpc docs

- content/exchange/index.md
- content/rackspace-email-archiving/index.md
- content/rackspace-email/index.md
- content/sharepoint/index.md
Fixes #1486 
Adding a section of general Cloud Office Control Panel links to each product intro page, except for Office 365, which I'm pretty sure works differently, and Skype for Business for the same reason.
> Add Cloud Office CP basics section to intro pages

- CONTRIBUTING.md
- Not associated with an issue
Open to suggestions on how best to do this. This is something we can easily fix for contributors when we perform reviews, but articles won't build unless metadata is included.
> Make metadata example more general

- content/rackspace-metrics/create-a-grafana-dashboard-for-rackspace-metrics.md
I am one of the developer in Rackspace Metrics team. We are dropping support for Enums metrics and thus would like to remove any publicly facing articles that mention Enums.
thanks,
-shinta
> remove enums mention as its support is discontinued

- content/rackspace-monitoring/available-checks-for-rackspace-monitoring.md
Added clarification so that the readers is aware that Cloud Control panel only contains a subset of available Rackspace Monitoring checks.
> clarification on checks in cloud control panel

- content/rackspace-metrics/integrate-statsd-with-rackspace-metrics.md
Based on user feedback, added information about ways to visualize the metrics.  Added clarification that Rackspace Intelligence does not yet support StatsD metrics.
> information about how to retrieve the metrics

- content/cloud-databases/choosing-the-right-database-with-rackspace-cloud-databases.md
In the previous PR, all references to 5.7 had not been removed.
> Removing reference to Percona 5.7

- content/cloud-servers/install-mysql-on-windows-server-2008-r2-and-2012.md
noticed the issue in the strider tests; audit date used ` instead of ', noticed the note had the wrong syntax
> minor proofing fixes

- content/rackspace-monitoring/install-and-configure-the-rackspace-monitoring-agent.md
Found more link broken from the developer guide re-structuring.
Pushed the link to install step up because dedicated support reported that the Intelligence link won't work for them because the UI access is still not permitted at this point.
> fixed link, minor content consolidation

- content/FAWS/task-based-article-template.md
Adding folder with template so that I can point to it from within the FAWS beta migration wiki at https://one.rackspace.com/display/OPS/MT+-+Technical+Documentation
> Add FAWS folder with article template

- content/cloud-servers/troubleshoot-remote-access-to-sql-server.md
Fixes #1760 
Nothing changed from 2012 to the 2014 and 2016 versions to require addition text, so just adding the version numbers to the appropriate section.
> add version numbers for 2014 and 2016

- content/cloud-networks/permissions-matrix-for-cloud-networks.md
Trent investigated for me, and apparently Floating IP has died? I'm checking to see if it should be removed from the API reference, but he said it definitely should go from the RBAC article.
Fixes #1849
> remove rbac floating ip section

- content/skype-for-business/set-up-dns-records-for-cloud-office-email-and-skype-for-business.md
fixes #1794 
The confusing asterisks in the autodiscover code line were meant to italicize *example.com*, but because they were in code, the asterisks displayed.
Removed the asterisks and also fixed the formatting on a note.
> remove asterisks from code, edit note formatting

- content/cloud-databases/using-ssl-with-your-cloud-database-instance.md
The argument for setting the SSL CA should be `--ssl-ca=...` not `-ssl-ca=...`
From the [MySQL docs](https://dev.mysql.com/doc/refman/5.6/en/secure-connection-options.html#option_general_ssl-ca):
> 
> --ssl-ca=file_name
> 
> The path to a file in PEM format that contains a list of trusted SSL certificate authorities. This option implies --ssl.
> Corrected The MySQL SSL CA Argument

- content/dedicated-hosting/add-new-vpn-user-myrackspace-portal.md
- content/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops.md
- content/dedicated-hosting/network-device-reboot-faq.md
- content/dedicated-hosting/rhel-and-centos-subscription-options-in-linux-infrastructures.md
The "type" metadata should say article instead of product for all of the dedicated articles.
> Update metadata in Dedicated articles

- content/rpc-openstack/index.md
Fixes #1936 
Repair broken links on the RPC - OpenStack intro page
Note, the OpenStack support page on rackspace.com doesn't exist anymore, so I changed the link to the main support page, which lists the contact info for RPC support.
Also, the OpenStack Ansible installation guide for Kilo is gone. I guess it passed EOL?
> repair broken links

- content/cloud-servers/migrating-to-a-general-purpose-or-io-server.md
It looks like someone did a "find/replace" from "Performance" to "General Purpose," which is not appropriate as the disk allotment and resize policies are very different on GP.
> Removing outdated and inaccurate information

- content/cloud-servers/migrating-to-a-general-purpose-or-io-server.md
The "system disk/data disk" dichotomy, which is important for Performance, is not needed for General Purpose servers, which only have a single disk. I/O servers do have data disks, so I left the data disk verbiage where appropriate.
> Remove system disk phrasing, grammar

- content/cloud-servers/before-you-move-to-general-purpose-or-io-cloud-server-checklist.md
- content/cloud-servers/considerations-for-migrating-to-a-general-purpose-or-io-cloud-server.md
Same problem as previously cited, we did a find/replace from "Performance" to "General Purpose," but the disk allotment and resize policy are drastically different between these flavors, so there is a lot of inaccurate information.
> updated to fit "General Purpose" flavor

- content/cloud-servers/installing-python-novaclient-on-windows.md
The installation command for pip installs a new version of nova that is not compatible.  Using version 3.3.0 the nova client can successfully connect to our API in Windows.
> updated pip install command

- content/cloud-servers/new-features-in-general-purpose-and-work-optimized-cloud-servers.md
Removed the "data disks are not captured by imaging operation" section as it's well-covered by the "Disk structure" section and linked article. Corrected information that was accurate for older "Performance" servers, but not for "General Purpose" flavor servers.
> Corrected information about GP, removed section

- content/cloud-backup/rackspace-cloud-backup-vs-cloud-server-image-backups.md
Removed inappropriate GP verbiage, caveats for the imaging process, more clarity on file-based vs. image-based backups.
> Remove inappropriate GP verbiage, edits for clarity

- content/cloud-servers/cloud-servers-faq.md
Adding some work-optimized server verbiage and removed inaccurate info about General Purpose servers, as well as eliminating the whole vCPU section as it is obsolete (that section appears to have been written entirely about first-gen).
> add work-optimized server verbiage

- content/cloud-files/cloud-files-streaming-simple-flash-files.md
Please refer to: https://support.rackspace.com/how-to/cloud-files-faq/ --> Account Services section. 
Cloud Files CDN does not support exposing a custom crossdomain.xml file, as this is a required file by the OpenStack Swift project. OpenStack Swift uses this as a global configuration file for the installation, and can not be modified for multiple tenants, such as our Public Cloud. Creating a crossdomain.xml file in the root of a container will not make it available for use via Cloud Files CDN. The default crossdomain.xml file is returned by origin instead.
> rm conflicting information re crossdomain.xml mod

- content/cloud-servers/rackspace-cloud-essentials-choosing-the-right-size-cloud-server.md
Changes:
- No longer recommending Standard flavor for anything.
- Expanding recommendation of General Purpose flavor.
- Removing reference to OnMetal Compute and adding OnMetal General Purpose, as OnMetal v2 does not offer a Compute flavor.
- Removing Munin link, as Rackspace Monitoring can do the same thing.
- Removing links to performance testing and scaling articles as their information is seriously out of date.
- Corrected random typos.
Long-term, would recommend getting a Windows admin involved to add a "Performance Testing in Windows" section.
> Updated flavor recommendations

- content/cloud-files/configure-w3-total-cache-for-wordpress-with-rackspace-cloud-files-cdn.md
Adding a CNAME record for an SSL CDN url results in SSL warning so it isn't considered usable (see the last point here: https://support.rackspace.com/how-to/using-cnames-with-cloud-files-containers/ )
Enabling only the HTTP version of aliasing in Wordpress is not possible so this section needs to go.
> Removing the optional CNAME set up section

- content/rackspace-email/prepare-pop-imap-exchange-mail-servers-for-migration.md
Links to other how-to articles were broken. Missing the forward slash before how-to in the link format
> fix broken links

- content/rackspace-email/adding-a-rackspace-email-group-list.md
- content/rackspace-email/adding-an-alias-with-rackspace-email.md
- content/rackspace-email/rackspace-webmail.md
- content/retired-articles/rackspace-email-mailbox-features.md
Will make sure these conform to Cloud Office style and standards at a later date.
The same must be done for Exchange Mailbox features article.
Fixes issue #2051
> Retire Rackspace Email Features article

- content/retired-articles/use-a-custom-kernel-with-pv-grub.md
discovered that this article I was going to do a full audit on had been retired months ago, but the article wasn't moved to the retired articles folder.
> move retired article to correct folder and fix metadata

- content/rackspace-email/rackspace-webmail.md
Makes consistent use of "you" rather than "they" or "users", per the style guidelines. Also fixes a few other typos, and removes "Mobile Sync" references in favor of "Rackspace Email Plus" (since Mobile Sync is no longer offered as a standalone service, but instead is bundled into the Rackspace Email Plus product).
> change 3rd to 2nd person, fix typos, change mobilesync references to rse+

- content/cloud-databases/managing-cloud-databases-configuration-groups-in-the-cloud-control-panel.md
**Note:** Applying configurations to Cloud Databases HA groups is not yet supported in the Cloud Control Panel. You can create the configuration group, but it must be applied via the API. The Cloud Databases Developer Guide has details on how to [attach configuration groups to HA groups via the API](https://developer.rackspace.com/docs/cloud-databases/v1/developer-guide/#attach-configuration-group-to-ha-instance).
This doesn't appear to be the case anymore as I have been able to add custom configurations to my own HA group and a customer HA group via the mycloud portal.
-DaPriest Watson
> Remove HA Group Note for configs via portal

- content/general/linux-os-mitigations-against-cpu-speculative-execution-vulnerabilities.md
the sentence "A kernel update to mitigate the exploits on the supported Linux® distributions at Rackspace (Red Hat® and CentOS® 6.7+ & 7.3+; Ubuntu® 14.04 & 16.04 LTS) has been released."
should be replaced with this sentence:
"Kernel updates to mitigate specific variants of the exploits on the supported Linux® distributions at Rackspace (Red Hat® and CentOS® 6.7+ & 7.3+; Ubuntu® 14.04 & 16.04 LTS) have been released."
> Changed 2nd para from singular to plural per Marc

- content/rackspace-monitoring/getting-started-with-rackspace-monitoring-cli.md
The link to the Rackspace Monitoring FAQ ended as a 404 to https://support.rackspace.com/how-to/rackspace-monitoring/-faq/, this is a 301 response from the url from https://support.rackspace.com/how-to/cloud-monitoring-faq/, that will also need to be fixed but I'm not aware of where the redirects are located.
The correct article is https://support.rackspace.com/how-to/rackspace-monitoring-faq/ and this should fix that.
> Fix deadlink

- content/cloud-networks/common-network-troubleshooting-tools.md
This clears up possibly confusion that might happen if a Window user tries to run `traceroute` directly.
```
C:\Users\0x91>traceroute
'traceroute' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\0x91>tracert
Usage: tracert [-d] [-h maximum_hops] [-j host-list] [-w timeout]
[-R] [-S srcaddr] [-4] [-6] target_name
Options:
-d                 Do not resolve addresses to hostnames.
-h maximum_hops    Maximum number of hops to search for target.
-j host-list       Loose source route along host-list (IPv4-only).
-w timeout         Wait timeout milliseconds for each reply.
-R                 Trace round-trip path (IPv6-only).
-S srcaddr         Source address to use (IPv6-only).
-4                 Force using IPv4.
-6                 Force using …
```
> Add note regarding Windows tracert name

- content/cloud-servers/checking-listening-ports-with-netstat.md
`isof` should really be the `lsof` command on this page.
> Fix typo: lsof command

- content/cloud-networks/cloud-networks-faq.md
FAQ Question had a newline before the last word of the question
which would drop the end of the question into the answer
section.
> Fixing FAQ question

- content/cloud-servers/delete-a-server.md
- content/cloud-servers/reboot-a-server.md
- content/cloud-servers/reset-a-server-password.md
- content/cloud-servers/resize-standard-and-general-purpose-servers.md
- This PR is a part of my full audit of the "Manage a server" and "Manage your server" articles. Since I am retiring the "Manage your server" article, I have updated the articles linked to that one to match the title of their new parent article, "Manage a server".
> Rename manage Cloud Server articles to match parent.

- content/cloud-orchestration/building-cloud-orchestration-templates.md
the example contains an invalid IPv4 address, which won't validate.
> Changing the example for Cloud DNS resource

- content/cloud-backup/install-or-update-the-cloud-backup-agent-on-linux.md
Customers should always use secure links to agentrepo.
There is a new keyring-latest package for apt-based installs, and new instructions for installing it.
> update deb keyring instructions and use secure links

- content/cloud-networks/cloud-servers-attaching-and-detaching-networks.md
OnMetal and RackConnect v2 servers can't attach and detach networks
> Adding exceptions

- content/cloud-servers/logging-in-with-an-ssh-private-key-on-windows.md
Added clarification that could trip less technical customers up: "To finish, click the "Save private key" button, and then enter a file name in the "Save private key as:" dialog box to save it for use with PuTTY."
> Add clarification

- content/cloud-servers/installing-an-ssl-certificate-on-apache.md
Article said that the CSR was to be installed on the server.  That is not true as the CSR is used to purchase the SSL, then the SSL package is installed on the server.
> Update CSR information

- content/cloud-images/transferring-images-between-regions-of-the-rackspace-open-cloud-with-pitchfork.md
- content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md
Retiring domain pitchfork.cloudapi.co, replaced by pitchfork.rax.io.
> Update DNS Record for pitchfork.cloudapi.co to pitchfork.rax.io

- content/cloud-databases/manage-cloud-databases-ha-groups-in-the-cloud-control-panel.md
- content/cloud-files/set-up-a-static-website-with-cloud-files.md
- content/cloud-servers/installing-mysql-server-on-ubuntu.md
- content/cloud-servers/keep-cloud-serves-up-to-date.md
- content/cloud-servers/linux-server-security-best-practices.md
- content/cloud-servers/rackspace-cloud-essentials-checking-a-server-s-ssh-host-fingerprint-with-the-web-console.md
- content/cloud-servers/scheduled-images-faq.md
- content/cloud-servers/set-up-apache-virtual-hosts-on-ubuntu.md
- content/cloud-servers/troubleshoot-a-downed-linux-cloud-server.md
- content/cloud-servers/troubleshoot-a-downed-windows-cloud-server.md
- content/cloud-servers/understanding-logrotate-utility.md
- content/retired-articles/rescue-mode-on-windows-servers.md
- content/skype-for-business/set-up-dns-records-for-cloud-office-skype-for-business.md
The docs have some pages with repeated 'the' articles.
```bash
grep ' the the ' -irl *
```
> Fix typos of repeated consecutive 'the'

- content/cloud-files/install-the-swiftly-client-for-cloud-files.md
Some examples in this article do not follow the style guide for code placeholders because the swiftly commands contain the literal text "<item>" which is very similar.
> Add configuration and examples to article

- content/cloud-images/preparing-an-image-for-import-into-the-rackspace-opencloud.md
As of this week, the image import limit has been raised from 40GB to 160GB.
> Raise image import limit

- content/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops.md
Removed Ubuntu 14.04 LTS as that is now End of Life
Removed duplicate listing of Ubuntu 18.04 LTS - the bottom one in "Managed Operations", since listing at the top will include Managed Operations
> Ubuntu LTS Updates

- content/cloud-servers/hidden-base-images.md
Update Retired Images for Ubuntu 14.04, Fedora 27/28 and Debian 8
> Update Retired Images

- content/rackspace-email/rackspace-directory-sync-install-and-configure.md
Changed "Communications between the Active Directory password hook and
Directory Sync **_is_** secured with Microsoft Windows Communication
Foundation (WCF).." to "Communications between the Active Directory password hook and
Directory Sync **_are_** secured with Microsoft Windows Communication
Foundation (WCF).." since the subject of the sentence, "Communications", is plural.
> Grammar: change "is" to "are"

- content/cloud-servers/network-configuration-for-eth0-changed-to-dhcp-after-upgrading-rhel-centos.md
* Add step to check `nova-agent` is running / starting on boot (essential for a network reset)
* "reset the network application programming interface (API) call" makes no sense - what you are doing is "reset the network", but you are doing it _via_ the API. You are not resetting the API :) corrected that wording...
* Adds a note about not disconnecting your existing network(s)
* Adds instruction for triggering the reset locally on the server
> Update EL7 cloud-init issue docs with nova-agent ref + cloud network warning 

- content/exchange/rackspace-directory-sync-administrators-guide.md
with Exchange OnPrem synchronized, setting the proxy address attribute to a capital SMTP will cause issues. Updated instances of SMTP to lower case smtp instead.
> Update SMTP to smtp in Alternate email addresses

- content/cloud-servers/how-to-install-a-lamp-stack-on-centos-fedora-or-red-hat.md
- content/cloud-servers/how-to-install-a-lamp-stack-on-rhel-6-based-distributions.md
Changes made to prepare for a new article specifically for RHEL 7 based distros. I also noticed some issues when reviewing this article as a reference. . I've outlined the changes below. 
- Proposed changes to article description to specify RHEL 6 based distros
- Added that sudo/admin access is needed on the server
- Added mysql_secure_installation question and answers to one-liner with accurate questions and answers
- Updated manual mysql_secure_installation section with accurate questions and answers
- Added iptables rules for port 443 to one-liner and manual method. 
Tested on CentOS 6 cloud server.
> Update article to specify RHEL 6 based distros

- content/cloud-servers/centos-7-apache-and-php-install.md
Remi is not a supported 3rd party repo. 
https://support.rackspace.com/how-to/linux-spheres-of-support-for-dedicated-and-managed-ops/#third-party-repositories
Updating article to give instructions on how to install php 7.3 from the IUS repos. 
Additionally, with php 7.3, certain modules were either deprecated or baked into php 7.3 so a few of the modules listed do not install. 
Specifically: mcrypt, curl, zip, fileinfo
The mysql module is installed with mysqlnd so that has been updated as well. 
Added more commonly seen php 7.3 modules including bcmath, mbstring, and soap
> Update with supported repo

- content/cloud-orchestration/use-rackspace-orchestration-to-build-a-wordpress-stack.md
I noticed a few minor errors and some suggestions, but the initial pull had already been merged. 
Line 16 - lsycnd should be lsyncd
Lines 21-32 - Formatting on dev page seemed off.
Lines 46-53 - Bold on each section before the parenthesis for easier reading
Lines 54-65 - Bold for sections for readability
Line 63 - parenthesis and content in line
Line 108 - Stray asterisk on A/AAAA
Line 119 - Remove comma after live.
Line 119 -Specify that their local host file was modified to access so the changes aren't made on the server host file.
Line 122 - Bold http://yourdomain.com/wp-admin for readability
+189 - If you need to add more server nodes, copy the code from section 5 and paste it at the end of the /etc/lsyncd/lsync.conf.lua file and edit to include the additional server's ServiceNet IP …
> Fix formatting and spelling

- content/cloud-servers/install-a-lamp-stack-on-debian-or-ubuntu-based-distributions.md
There was a minor formatting issue at the top of the article where the important box was blank and the important info had escaped the box.
> Fix minor issue with formatting

- content/cloud-servers/linux-device-does-not-show-the-correct-disk-space-after-a-resize.md
Fixed formatting for terminal output on article. 
Also, I added a note box under the command example for clarification.  I think that line might have been in a previous iteration of the article before it was submitted. Figured it couldn't hurt to add the extra info, so I added it to the page.
> Fix formatting and add note for filesystem command

- content/retired-articles/sample-ruby-application-for-cloud-files.md
This work addresses this JIRA https://jira.rax.io/browse/INFODEV-3921.
Retire file after research provided by Maeve Goetz that using the code does work but produces errors. Here is email from Maeve on 5/27:
Hi Catherine,
Sorry for the delay replying, took a little while to be able to carve out some time to get the code on the support page tested.  It does still work, though the gem it requires throws warnings about part of it being obsolete, So, I don't think there will be an issue getting rid of the page.  
We also have information on https://developer.rackspace.com/docs/cloud-files/quickstart/ for using Ruby with Cloud Files that seems to be more up-to-date than the support page you referenced.
Thanks again for reaching out and again, I'm sorry we took so long to get back with you.
- …
> Retire Cloud Files Ruby sample article

- content/rackconnect/rackconnect-global-faq.md
Thank you so much for getting this done! I’m sorry, I didn’t get a chance to look at it yesterday. Can you please ask for a few minor edits to be made?
What is RackConnect Global?
Please remove the space in “low- latency” – it should be “low-latency”.
Why should I care about avoiding the public Internet?
Please add to “This flow of information is susceptible”, to  “This flow of information is susceptible to intrusion.”
How does RackConnect Global work?
Please remove the space in “connectivity- rich” – it should be “connectivity-rich”.
Who is the audience for RackConnect Global, and what pain points does it solve?
Please change “leveraging the RackConnect Global Any-to-Any offering” to “RackConnect Global’s Any-to-Any connectivity”
Thanks!
cyr note: on the last request, I did not use the …
> Requested changes from SME

- content/cloud-servers/start-a-console-session.md
Since 2016, the Cloud Control Panel uses the novnc console (NOT java). Removed java/XVP references.
> Remove references to java/XVP

- content/cloud-servers/install-epel-and-additional-repositories-on-centos-and-red-hat.md
The old URLs (e.g. https://centos7.iuscommunity.org/ius-release.rpm,
https://rhel7.iuscommunity.org/ius-release.rpm) are broken.
See commit 5b1bf8e133fef3c12b61024df97d76df43888c81 of
https://github.com/iuscommunity/automation-examples
> Update IUS release package URL

- basic-iptables-firewall-management.md
Just a minor fix to formatting on the document,  The code block did not properly format under the line:
If you haven't configured any rules yet, the output looks similar to the following example:
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
> Fix formatting

- content/rackspace-email/email-migration-services.md
JIRA 6087
Special characters in mailbox folder names cause email migration to fail, so this PR adds a warning in the prerequisites section to remove any special characters from folder names.
> add warning about mailbox names

- content/retired-articles/swift-filesystem-for-hadoop.md
JIRA 6105
We don't offer Big Data solutions for public cloud anymore, so this article is no longer relevant.
> retire deprecated article

- content/cloud-load-balancers/configure-SSL-certificates-on-cloud-load-balancers.md
Not sure how to fix this, but on the live page, under the "Apply the SSL certificate to a Cloud Load Balancer", the step to Save Configuration is numbered as Step 1, but the code indicates that it's properly labeled as Step 5.
Also, I added an empty line under the table to help space the section out a bit..
> Fix steps displayed on production page

- content/cloud-block-storage/minimizing-the-impact-of-cloud-block-storage-maintenance.md
Customers do not need to delete their server to replace their bfv system disk.
> Update instructions on cloning system disk
