- content/cloud-dns/changing-dns-settings-on-linux.md
- content/cloud-servers/centos-hostname-change.md
- content/cloud-servers/changing-dns-settings-on-linux.md
- content/cloud-servers/checking-cloud-status.md
- content/cloud-servers/checking-linux-file-permissions-with-ls.md
- content/cloud-servers/checking-listening-ports-with-netstat.md
- content/cloud-servers/checking-running-services-on-linux.md
- content/general/change-account-information.md
part 4 (?) of the servers folder: moved a DNS article to DNS, and an account article to general. Fixed a lot of headers and code formatting.
> Servers content audit

- content/rackspace-intelligence/creating-custom-graphs-of-activity-in-rackspace-intelligence.md
- content/rackspace-intelligence/examining-the-log-of-alerts-suppressed-by-rackspace-intelligence.md
- content/rackspace-intelligence/getting-started-with-rackspace-intelligence-for-dedicated-accounts.md
- content/rackspace-intelligence/getting-started-with-rackspace-intelligence-for-the-cloud.md
For the first 5 Rackspace Intelligence articles, these commits improve spelling, spacing, headings, and links to API doc.
> Rackspace Intelligence post-migration audit, part 1

- content/cloud-backup/cloud-backup-faq.md
- content/cloud-big-data/cloud-big-data-faq.md
- content/cloud-block-storage/cloud-block-storage-faq.md
- content/cloud-databases/cloud-databases-faq.md
- content/cloud-dns/cloud-dns-faq.md
- content/cloud-files/cloud-files-faq.md
- content/cloud-images/cloud-images-faq.md
- content/cloud-load-balancers/cloud-load-balancers-faq.md
- content/cloud-monitoring/cloud-monitoring-faq.md
- content/cloud-networks/cloud-networks-faq.md
- content/cloud-orchestration/cloud-orchestration-faq.md
- content/cloud-servers/cloud-hosting-faq.md
- content/cloud-servers/cloud-servers-faq.md
- content/cloud-sites/cloud-sites-faq.md
- content/exchange/exchange-faq.md
- content/managed-operations/managed-operations-faq.md
- content/managed-vmware-services/managed-vmware-services-faq.md
- content/rackconnect/rackconnect-faq.md
- content/rackconnect/rackconnect-v20-faq.md
- content/rackspace-auto-scale/rackspace-auto-scale-faq.md
- content/rackspace-email-archiving/email-archiving-faq.md
- content/rackspace-intelligence/rackspace-intelligence-faq.md
- content/rpc-microsoft/microsoft-private-cloud-faq.md
- content/rpc-openstack/rpc-openstack-faq.md
- content/sharepoint/sharepoint-faq.md
- content/skype-for-business/skype-for-business-faq.md
This removes extra hyphens in FAQ titles.
> Remove extra hyphens from FAQ titles.

- content/rackconnect/access-the-rackconnect-management-interface.md
- content/rackconnect/accessing-rackconnect-cloud-servers.md
- content/rackconnect/associate-a-cloud-account-with-rackconnect-v30.md
- content/rackconnect/cloud-orchestration-support-for-rackconnect-v30.md
- content/rackconnect/cloud-server-images-for-use-with-rackconnect-v20.md
- content/rackconnect/comparing-rackconnect-v30-and-rackconnect-v20.md
- content/rackconnect/rackconnect.md
> Update seven articles

- content/cloud-backup/best-practices-for-backing-up-your-data-cloud-block-storage-versus-cloud-backup.md
- content/cloud-backup/cloud-backup-agent-logging-basics.md
- content/cloud-backup/cloud-backup-faq.md
- content/cloud-backup/cloud-backup-troubleshooting.md
- content/cloud-backup/create-a-maintenance-backup-plan-in-sql-server-2008-r2-using-the-wizard.md
- content/cloud-backup/rackspace-cloud-backup-backing-up-databases.md
- content/cloud-backup/rackspace-cloud-backup-backup-actions-0.md
- content/cloud-backup/rackspace-cloud-backup-create-a-backup-0.md
- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-linux.md
- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation.md
- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows.md
- content/cloud-backup/rackspace-cloud-backup-overview.md
- content/cloud-backup/rackspace-cloud-backup-preferences-0.md
- content/cloud-backup/rackspace-cloud-backup-system-actions.md
- content/cloud-backup/rackspace-cloud-backup-view-backup-information.md
- content/cloud-backup/rackspace-cloud-backup-vs-cloud-server-image-backups.md
- content/cloud-backup/recommended-cloud-backup-filedirectory-level-configuration-for-a-linux-server.md
- content/cloud-backup/update-the-rackspace-cloud-backup-agent.md
A series of edits to the Cloud Backup articles. Fix link titles, changed title naming conventions to be more general. Fix various formatting issues. Fix several links.
> Cloud backup - Nate edits

- content/cloud-backup/rackspace-cloud-backup-backing-up-databases.md
- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-linux.md
Fix link names. Ensure new titles are visible. Fix metadata.
> Small tweaks to articles.

- content/cloud-sites/add-impersonation-for-aspupload-on-cloud-sites.md
Link was just an example and did not point to a real URL.
> "Remove link and add code tags."

- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-linux.md
- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows.md
- content/cloud-backup/rackspace-cloud-backup-view-backup-information.md
- content/cloud-backup/rackspace-cloud-backup-vs-cloud-server-image-backups.md
Fix various issues I may have missed from the first pass, for example, link titles I missed, formatting issues within the article I missed, and various typos.
> Last pass through Cloud Backup audit

- content/cloud-backup/rackspace-cloud-backup-overview.md
- content/cloud-block-storage/cloud-block-storage.md
- content/cloud-databases/cloud-databases-developer-resources-and-how-to-articles.md
- content/cloud-files/cloud-files-faq.md
- content/cloud-files/cloud-files-how-to-articles-other-resources.md
- content/cloud-orchestration/permissions-matrix-for-cloud-orchestration.md
- content/cloud-servers/cloud-servers-how-to-articles-other-resources.md
- content/cloud-servers/developer-faqs.md
- content/cloud-servers/general-purpose-cloud-servers-how-to-articles-and-other-resources.md
- content/cloud-servers/getting-started-with-role-based-access-control-rbac-0.md
- content/cloud-servers/known-issues-and-suggested-workarounds-role-based-access-control-rbac.md
- content/cloud-servers/objectrocket-documentation.md
- content/cloud-sites/important-scheduled-maintenance-dfw-environment-migration.md
- content/managed-operations/managed-operations-faq.md
- content/rackspace-email/rackspace-email-faq.md
- content/rackspace-email/webmail-dropbox-integration-faqs.md
This one probably needs a careful look.
> Robin fix FAQs

- content/rackspace-intelligence/learning-the-rackspace-intelligence-vocabulary.md
- content/rackspace-intelligence/log-in-to-rackspace-intelligence-for-dedicated-accounts.md
- content/rackspace-intelligence/logging-in-to-the-rackspace-intelligence-dashboard.md
- content/rackspace-intelligence/monitoring-entities-with-rackspace-intelligence.md
- content/rackspace-intelligence/monitoring-open-alerts-with-rackspace-intelligence.md
Adding missing links, headings, bolding, and other formatting.
> Rackspace Intelligence post-migration audit, part 2

- content/cloud-files/cloud-files-faq.md
Front matter must begin and end with '---'
> fix frontmatter in cloud files faq

- content/rackspace-intelligence/preparing-to-use-rackspace-intelligence.md
- content/rackspace-intelligence/rackspace-intelligence-faq.md
- content/rackspace-intelligence/set-up-a-server-to-work-with-rackspace-intelligence.md
- content/rackspace-intelligence/setting-up-a-database-to-work-with-rackspace-intelligence.md
Improve headings, links, and bolding.
> Rackspace Intelligence post-migration audit, part 3

- content/rackspace-intelligence/understanding-the-rackspace-intelligence-dashboard-user-interface.md
- content/rackspace-intelligence/understanding-the-rackspace-intelligence-user-interface-for-dedicated-accounts.md
- content/rackspace-intelligence/viewing-and-creating-graphs-of-activity-in-rackspace-intelligence-for-dedicated-accounts.md
- content/rackspace-intelligence/working-with-alarms-checks-entities-notifications-and-notification-plans-in-rackspace.md
Correct bolding; delete internal links.
> Rackspace Intelligence post-migration audit, part 4

- content/rackspace-intelligence/working-with-alarms.md
Delete internal links & link to API doc in new location.
> Rackspace Intelligence post-migration audit, part 5

- content/cloud-monitoring/detailed-permissions-matrix-for-rackspace-monitoring.md
Reformatted entire table using template used for Cloud Images, removed images showing checkmarks. fixed syntax
> reformat tables for permissions matrix, fix typos and links

- content/cloud-servers/configuring-mysql-server-on-centos.md
one link fix plus tutorial for kyle ;)
> fix link formatting

- content/rackconnect/introducing-rackconnect-v20.md
- content/rackconnect/introducing-rackconnect-v30.md
- content/rackconnect/managing-rackconnect-v20-network-policies.md
- content/rackconnect/multiple-ssl-certificates-on-a-single-rackconnected-cloud-server-pat.md
- content/rackconnect/new-features-available-in-rackconnect-v30.md
- content/rackconnect/rackconnect-network-device-comparison.md
> Make fixes to migrated files

- content/cloud-sites/rackspace-cloud-sites-essentials-cloud-sites-technologies.md
Please pull this one before the -2 one.
> Fix one case of broken image URLs.

- content/cloud-backup/rackspace-cloud-backup-preferences-0.md
- content/cloud-orchestration/quick-set-up-with-rackspace-cloud-orchestration.md
- content/cloud-servers/logging-in-with-an-ssh-private-key-on-windows.md
- content/cloud-servers/managing-my-server.md
- content/cloud-servers/migrate-a-first-generation-server-to-a-next-generation-server-with-minimal-downtime.md
- content/cloud-servers/multi-factor-authentication-from-the-cloud-control-panel.md
- content/cloud-servers/removing-networks-from-a-cloud-server-0.md
- content/cloud-sites/getting-started-with-cloud-sites-getting-fanatical-support.md
- content/cloud-sites/net-45-in-cloud-sites.md
- content/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2010.md
- content/exchange/manually-configure-outlook-2007-for-email-hosted-on-exchange-2010.md
- content/exchange/manually-configure-outlook-2007-for-email-hosted-on-exchange-2013.md
- content/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2007.md
- content/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013.md
- content/rackconnect/comparing-rackconnect-v30-and-rackconnect-v20.md
- content/rackspace-intelligence/monitoring-entities-with-rackspace-intelligence.md
- content/rackspace-intelligence/monitoring-open-alerts-with-rackspace-intelligence.md
- content/rackspace-intelligence/understanding-the-rackspace-intelligence-dashboard-user-interface.md
> Fix several more cases of broken links.

- content/cloud-files/cloud-files-how-to-articles-other-resources.md
Remove outdated link and update another
> Update cloud-files-how-to-articles-other-resources.md content

- content/cloud-queues/cloud-queues-message-patterns.md
Fix Audit md syntax.
Reformat variation descriptions to clarify relationship to steps.
> Fix formatting

- content/rackconnect/rackconnect-global-faq.md
> Change header level

- content/cloud-databases/choosing-the-right-database-with-rackspace-cloud-databases.md
> Cloud databases - Nate Edits

- content/cloud-databases/permissions-matrix-for-cloud-databases.md
- content/cloud-databases/scheduled-backups-for-cloud-databases.md
Table is on permissions matrix article.
Links on scheduled back article.
> Fix links in scheduled backup article. Fix formatting of table.

- content/cloud-queues/cloud-queues-overview.md
Change use case labels to headers
> Make headers sentence  case

- content/cloud-queues/setting-up-a-producer-consumer-model-with-cloud-queues.md
Update links to API docs on DRC
> Fix header, sentence case, code samples

- content/cloud-queues/tips-for-monitoring-your-queues-in-cloud-queues.md
Clarified that you use API to submit an API request. 
Fix awkward wording in notes.
> Clarify intro text and note

- content/cloud-queues/setting-up-a-pub-sub-model-in-cloud-queues.md
Add intro sentence to article.
Corrected formatting in JSON response examples.
Removed future tense.
> Headers and code sample updates

- content/cloud-load-balancers/configure-a-load-balancer.md
Remove header for What is a load balancer so it's an intro paragraph.
Change "where to go from here" to next steps.
Update link to Cloud Files and CDN intro how-to article
> Remove top links and update next steps link

- content/cloud-sites/getting-started-with-cloud-sites-logging-into-the-control-panel.md
> “Change headers to sentence case.”

- content/cloud-servers/managing-my-server.md
> change header to h3

- content/exchange/add-an-activesync-or-bes-license.md
- content/exchange/add-multiple-contacts-to-exchange.md
- content/exchange/adding-a-microsoft-exchange-contact.md
- content/exchange/adding-microsoft-exchange-mailboxes-0.md
Formatting, structural, and some spelling improvements.
> Exchange post-migration audit: articles starting with A

- content/cloud-servers/migrating-an-application-based-on-backbonejs-nodejs-and-mongodb-from-amazon-web-services.md
Another servers article audit. This was my temp working branch while waiting for feedback on the failing travis build on my normal servers branch.
Just fixed the formatting of the lists and all items within the lists (additional paragraphs, code, images, links, etc)
> fix formatting of lists, links, images

- content/exchange/configure-email-clients-and-mobile-devices-for-email-hosted-on-exchange.md
- content/exchange/deleting-and-resending-blackberry-service-books-bes.md
For Exchange post-migration audit, these are all articles beginning with C and D. There are no Bs.
> Rose exchange

- content/cloud-sites/transfer-your-registered-domain-from-click-and-name-to-another-registrar.md
> "Change h2 headers to h3."

- content/cloud-sites/use-a-later-version-of-mysql-with-net-applications-on-cloud-sites.md
> "Remove internal links."

- content/cloud-servers/sample-logrotate-configuration-and-troubleshooting.md
- content/cloud-servers/scheduled-images-faq.md
- content/cloud-servers/securing-the-cloud-addressing-cloud-computing-security-concerns-with-private-cloud.md
- content/cloud-servers/set-up-a-two-server-glusterfs-array.md
- content/cloud-servers/set-up-apache-virtual-hosts-on-ubuntu.md
- content/cloud-servers/set-up-mysql-master-slave-replication.md
- content/cloud-servers/setting-up-a-mail-relay.md
- content/cloud-servers/setting-up-vyatta-vpn-with-policy-nat.md
- content/cloud-servers/should-i-upload-files-as-ascii-or-binary.md
- content/cloud-servers/simple-load-balancing-with-apache.md
- content/cloud-servers/start-a-console-session.md
- content/cloud-servers/support-ticket-statuses.md
- content/cloud-servers/swift-filesystem-for-hadoop.md
- content/cloud-servers/system-disk-and-data-disk-faq.md
- content/cloud-servers/systems-management-simplified-in-the-cloud.md
Helping Stephanie finish the Cloud Server audits. This is the first set of changes.
> Nate server edits (S letters)

- content/cloud-backup/cloud-backup-faq.md
Bold text for consistency.
Change italics on word to code.
> Small edits to Cloud Backup FAQ

- content/rackspace-email/adding-an-alias-with-rackspace-email.md
- content/rackspace-email/enable-email-archiving-cloud-office-control-panel.md
- content/rackspace-email/factors-that-affect-the-duration-of-email-migrations.md
- content/rackspace-email/fix-outlook-synchronization-errors.md
- content/rackspace-email/forced-ma-routing.md
> Make minor fixes to Rackspace Email articles

- content/cloud-servers/testing-network-services-with-netcat.md
- content/cloud-servers/the-hosting-spectrum-which-solution-fits-your-business.md
- content/cloud-servers/transferring-your-dns-hosting-to-rackspace.md
- content/cloud-servers/troubleshooting-dns-issues.md
Tweaks to articles starting with the latter T. No significant changes. Refer to commits for specific edits.
> Nate Server edits (T letters)

- content/cloud-databases/access-slow-query-and-general-logs-for-cloud-databases.md
- content/cloud-databases/cloud-databases-developer-resources-and-how-to-articles.md
- content/cloud-databases/connect-to-a-cloud-databases-instance.md
Perform one more pass through Cloud Databases. Fix any errors I may have missed the first time.
> Databases soft edits

- content/cloud-servers/mysql-connect-to-your-database-remotely.md
- content/cloud-servers/mysql-master-master-replication.md
- content/cloud-servers/mysql-replication-masterslave.md
- content/cloud-servers/mysql-resetting-a-lost-mysql-root-password.md
- content/cloud-servers/new-features-in-general-purpose-and-work-optimized-cloud-servers.md
- content/cloud-servers/next-generation-cloud-servers-migration-considerations-and-options.md
- content/cloud-servers/next-generation-cloud-servers-sample-code.md
- content/cloud-servers/nslookup-checking-dns-records-on-windows.md
- content/cloud-servers/objectrocket-documentation.md
Changed headers to h3, removed unnecessary html, fixed formatting for code, lists, notes, and links.
@catlook review please? :)
> Sf-servers-audit

- content/rackspace-email/general-information-cloud-office-control-panel.md
- content/rackspace-email/help-tool-for-hosted-email-and-skype-for-business.md
- content/rackspace-email/imap-and-pop-mail-protocol-comparison.md
- content/rackspace-email/introduction-to-mailgun-email-automation.md
- content/rackspace-email/items-migrated-during-an-cloud-office-migration.md
Please check and merge, @catlook
> Fix minor issues in Rackspace Email articles

- content/exchange/exchange-email-mailbox-features.md
- content/exchange/exchange-faq.md
- content/exchange/exchange.md
- content/exchange/imappop-to-exchange.md
There are no articles starting with F, G, H.
There are no articles starting with J, K, L.
M will be huge.
> Exchange post-migration audit: articles starting with E - I

- content/skype-for-business/hosted-microsoft-lync-at-rackspace-deployment-guide.md
> Fix Issue #268

- content/rackspace-email/cloud-office-control-panel.md
- content/rackspace-email/locking-down-ip-addresses-in-migrationwiz.md
- content/rackspace-email/manage-company-contacts-in-the-cloud-office-control-panel.md
- content/rackspace-email/manage-domain-aliases-with-the-cloud-office-control-panel.md
- content/rackspace-email/manage-domains-cloud-office-control-panel.md
- content/rackspace-email/manage-email-administrators-with-the-cloud-office-control-panel.md
fix numbering, fix headings, remove outdated screenshots, etc.
> Fix migrated Rackspace Email articles

- content/rpc-microsoft/architecture-requirements-for-rackspace-private-cloud-powered-by-microsoft.md
- content/rpc-microsoft/microsoft-private-cloud-faq.md
- content/rpc-microsoft/rpc-microsoft.md
Cleaned up headings to H3
Changed tables to markdown format
> perform kc audit, clean up headings and update tables

- content/cloud-images/preparing-an-image-for-import-into-the-rackspace-opencloud.md
Reverts rackerlabs/rackspace-how-to#304
> Revert "Fix internal links."

- content/rpc-openstack/bare-metal-to-rackspace-private-cloud.md
> Remove html tags, header updates

- content/cloud-servers/add-and-remove-glusterfs-servers.md
- content/cloud-servers/adding-disk-space-after-resizing-a-windows-server-2012-cloud-server.md
- content/cloud-servers/application-and-load-testing-guidelines.md
- content/cloud-servers/backing-up-your-files-with-rsync.md
- content/cloud-servers/basic-cloud-server-security.md
Noticed a few mistakes while double-checking the live site.
> Server stragglers

- content/cloud-images/sharing-images-in-the-cloud-control-panel.md
- content/managed-operations/cloud-servers-with-managed-operations-support-for-windows.md
This removes a blank line at the top of one file and
reverts commit 5c2c75ce6e7485fe3a7532548da563018cf7eb71.
> fix broken front-matter

- content/rpc-openstack/apache-hadoop-on-rackspace-private-cloud.md
Add additional headers to the Hadoop installation and set up section
Add description for OpenStack architecture diagram
Miscellaneous edits
> Fix header titles and case, add more headers

- content/exchange/outlook-web-access-owa-for-exchange.md
- content/exchange/public-folders-availability-for-hosted-exchange-2013.md
- content/exchange/rackspace-directory-sync-administrators-guide.md
- content/exchange/rackspace-directory-sync-operation-guide.md
> Exchange post-migration audit: articles starting with O and P

- content/cloud-servers/view-and-reset-your-api-key.md
- content/cloud-servers/vnc-install.md
- content/cloud-servers/what-happens-if-i-do-not-supply-a-vat-id-number.md
- content/cloud-servers/what-is-new-with-onmetal-cloud-servers.md
- content/cloud-servers/windows-overview.md
- content/cloud-servers/windows-server-security-best-practices.md
- content/general/viewing-and-editing-user-information-for-your-account.md
- content/general/what-is-managed-colocation-from-rackspace.md
- content/general/when-am-i-billed-for-my-account.md
- content/general/when-is-managed-colocation-a-good-fit.md
- content/general/why-do-you-need-my-vat-id-number.md
Last bit of the servers folder V-W. Moved some account and billing articles to the general folder. Fixed formatting of images, code, lists, and notes.
> Final servers

- content/exchange/use-simple-email-setup-to-configure-ios-devices-for-email-hosted-on-exchange-2010.md
- content/exchange/working-with-public-folders-through-outlook-for-exchange-2007-and-2010.md
No X. No Y. No Z. That's everything for Exchange!
> Exchange post-migration audit: articles starting with U and W

- content/cloud-sites/cloud-sites.md
- content/cloud-sites/common-administrative-tasks-in-mssql-server.md
- content/cloud-sites/configure-your-cloud-sites-email-account-in-chatteremail.md
- content/cloud-sites/configure-your-cloud-sites-email-account-in-outlook-2000.md
- content/cloud-sites/configure-your-cloud-sites-email-account-on-your-iphone.md
- content/cloud-sites/connect-to-cloud-sites-via-sql-server-management-studio-express.md
- content/cloud-sites/connection-timeout-error-message-on-cloud-sites.md
- content/cloud-sites/controlling-access-to-linux-cloud-sites-based-on-the-client-ip-address.md
- content/cloud-sites/create-a-cron-job-to-back-up-a-cloud-sites-sql-server-database.md
- content/cloud-sites/create-a-database-user-with-read-only-access-for-sql-server-databases.md
- content/cloud-sites/create-a-domain-or-subdomain-that-points-to-a-folder-on-an-existing-cloud-sites-website.md
Some lingering issues in articles
> Survey audit

- content/cloud-sites/disable-caching-on-cloud-sites.md
- content/cloud-sites/dns-management-how-to-update-your-ip-address.md
- content/cloud-sites/does-the-rackspace-cloud-support-secure-email.md
- content/cloud-sites/enable-detailed-errors-in-classic-asp-and-server-side-errors-on-cloud-sites.md
- content/cloud-sites/enable-or-disable-a-cloud-sites-scheduled-task-cron-job.md
- content/cloud-sites/enabling-raw-logging-for-a-cloud-sites-website.md
- content/cloud-sites/file-permissions-on-cloud-sites.md
- content/cloud-sites/ftp-snapshot.md
- content/cloud-sites/getting-started-with-cloud-sites-accessing-billing-information.md
- content/cloud-sites/getting-started-with-cloud-sites-configuring-ssl-on-your-websites.md
- content/cloud-sites/getting-started-with-cloud-sites-creating-sub-domains-andor-domain-aliases.md
- content/cloud-sites/getting-started-with-cloud-sites-ftpsshfsftp-clients.md
- content/cloud-sites/getting-started-with-cloud-sites-getting-fanatical-support.md
Found some typos and html that hadn't been converted to markdown.
> Spot checking

- content/index.html
Also, use "set up" as verb form (setup is noun form) and make how-to in browser title consistent with how-to displayed on page.
> Clarify references to Cloud User Guide

- content/cloud-servers/migrate-to-rackspace-from-another-hosting-provider.md
This is an article I was working on before the migration. Making a few minor tweaks before I share the link with Trent.
> Small edits to migration article.

- content/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2007-and-2010.md
Otherwise, it's shoved far to the right.
> Add blank line so image begins AFTER Step 8.

- content/cloud-sites/modify-your-hosts-file.md
Found some spacing errors in one of the numbered lists.
> fix spacing in list

- content/cloud-images/detailed-permissions-matrix-for-cloud-images.md
- content/cloud-images/identifying-rackspace-standard-images.md
- content/cloud-images/preparing-an-image-for-import-into-the-rackspace-opencloud.md
- content/cloud-images/rackspace-standard-and-non-standard-images.md
- content/cloud-images/sharing-images-in-the-cloud-control-panel.md
- content/cloud-images/transferring-images-between-regions-of-the-rackspace-open-cloud.md
- content/cloud-images/use-swiftly-to-download-an-exported-image.md
Small edits to Cloud images article. Consists of changes not caught during the first audit.
> Small edits images

- content/cloud-load-balancers/permissions-matrix-for-cloud-load-balancers.md
- content/cloud-servers/rackspace-cloud-essentials-cloud-server-image-limitations.md
- content/cloud-servers/rackspace-cloud-essentials-what-are-your-name-servers.md
- content/cloud-sites/getting-started-with-cloud-sites-getting-fanatical-support.md
- content/rackconnect/rackconnect-faq.md
- content/rackconnect/rackconnect.md
- content/rackspace-intelligence/rackspace-intelligence.md
Fixing links as per Robin's script that found a few broken ones.
> Link fixes

- content/office-365/office-365.md
> Small tweaks- Office 365

- content/cloud-sites/como-modificar-mi-archivo-de-hosts.md
- content/cloud-sites/como-modifico-meus-arquivos-de-hosts.md
- content/cloud-sites/modify-your-hosts-file.md
Added the Spanish and Portuguese translations of the Modify your hosts file article.
> Es pt articles

- content/cloud-sites/como-modificar-mi-archivo-de-hosts.md
- content/cloud-sites/como-modifico-meus-arquivos-de-hosts.md
Noticed a stray English "and" in both articles so changed to "e" and "y", respectively.
> changed articles to spanish and portuguese, respectively

- content/cloud-sites/como-modifico-meus-arquivos-de-hosts.md
Found a formatting error in the PT list.
> fix formatting error in list

- content/rackspace-email-archiving/create-an-archive-audit-report.md
> Fix nested list in create archive audit report article.

- content/rackspace-email-archiving/add-and-edit-archive-users-in-cloud-office.md
This fixes a rendering issue with the nested list on this page.
> Robin fix nested list

- content/cloud-servers/migrate-to-rackspace-from-another-hosting-provider.md
>  Kelly's edits for "Migrate to Rackspace from another hosting provider."

- content/cloud-servers/about-cloud-server-images.md
- content/cloud-servers/use-a-custom-kernel-with-pv-grub.md
Per the request from Jeffrey Rangel to return the "Use a custom kernel wth pv-grub" article for customer use.
> add requested article for customer use

- content/cloud-servers/create-a-cloud-server.md
> fix spacing for nested image and note to format properly

- content/rpc-microsoft/rpc-microsoft-faq.md
Import content from microsoft-private-cloud-faq.md
> Import content

- CONTRIBUTING.md
- style-guidelines.md
I updated CONTRIBUTING.md with instructions that Rosie created, plus I added some writing guidelines that I had created for the Carina repo. Part of that addition is a separate style guidelines file. Please review and post comments.
> Update contributing.md file and add style guidelines file

- content/cloud-load-balancers/cloud-load-balancers-faq.md
Hi,
I've moved this FAQ higher up, as it didnt make sense to me to have this after instructions on how to setup termination, when to use etc.
> Move 'Do CLBs support SSL Termination'

- content/rackconnect/using-cloud-load-balancers-with-rackconnect.md
lbaasopsbot output from Stephen Lange on 2/8/2016:
!servicenetips lb dfw
[12:33] < LBaaSOpsBot> | ============================================================
[12:33] < LBaaSOpsBot> | DFW1
[12:33] < LBaaSOpsBot> | ============================================================
[12:33] < LBaaSOpsBot> | IP Block: 10.183.250.0/24
[12:33] < LBaaSOpsBot> | IP Block: 10.189.254.0/24
[12:33] < LBaaSOpsBot> | IP Block: 10.183.251.0/24
[12:33] < LBaaSOpsBot> | IP Block: 10.189.255.0/24
[12:33] < LBaaSOpsBot> | IP Block: 10.187.186.0/24
[12:33] < LBaaSOpsBot> | IP Block: 10.189.252.0/24
[12:33] < LBaaSOpsBot> | IP Block: 10.183.248.0/24
[12:39] <       slang> | !servicenetips lb ord
[12:39] < LBaaSOpsBot> | ============================================================
[12:39] < LBaaSOpsBot> | ORD1 …
> Update  IP listings for all regions using lbaasopsbot output

- content/cloud-backup/update-the-rackspace-cloud-backup-agent.md
This is an additional update for an article that Catherine updated based on a request. I'll ping Catherine to review and merge.
> Copy edit file for standards

- content/cloud-files/cloud-files-faq.md
Found an elusive typo and corrected it!
> fix typo and openstack capitalization

- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-linux.md
Copy edited. @cyrichardson, please review and merge. Again, please check (especially after merging) that the code blocks under the steps look right. Thanks!
> Edit install-update-backup-agent-linux

- content/rackspace-email/add-rackspace-email-mailboxes.md
Changed the Rackspace email password requirements for accuracy.
> Change password requirements for Rackspace Email

- CONTRIBUTING.md
> Copy edit the new image note

- content/cloud-sites/getting-started-with-cloud-sites-getting-fanatical-support.md
Uploaded and replaced a screenshot that was out-of-date.
> Update How-to screenshot

- content/cloud-files/set-up-a-static-website-with-cloud-files.md
> Fix broken image on static website article

- content/cloud-files/set-up-a-static-website-with-cloud-files.md
Instead of placing the image within the note directive. I've decided to place the image above the note directive.
> Fix formatting issue with "Static Website" image.

- content/cloud-files/configure-w3-total-cache-for-wordpress-with-rackspace-cloud-files-cdn.md
For some reason, images and sub-paragraphs were resetting the numbered list. So I've adjusted the spacing to see if it'll fix.
> trying to fix weird formatting issues on live page

- content/cloud-servers/new-features-in-general-purpose-and-work-optimized-cloud-servers.md
Noticed that the asterisk spacing was off in bold formatting. My Cloud Smart instructor had it up on the screen and it caught my eye!
> fix spacing of asterisks in bold formatting

- content/cloud-databases/scheduled-backups-for-cloud-databases.md
I noticed a few small things that needed to be fixed.
> small-edits-for-scheduled-backups-article

- content/cloud-servers/managing-your-server-resizing-standard-and-general-purpose-servers.md
The images in the list weren't indented with the bullets, so trying to fix that
> fix spacing of images in bulleted list to indent them

- content/cloud-databases/connect-to-a-cloud-databases-instance.md
Because an article should not begin with a heading!
> Add intro sentence

- content/cloud-files/back-up-data-with-cloud-files.md
The substep formatting in the second procedure needed to be fixed.
> Fix step numbering and image

- content/cloud-backup/rackspace-cloud-backup-backup-actions.md
- content/cloud-backup/rackspace-cloud-backup-overview.md
-Fix formatting issue with images appearing as code blocks
-Fix formatting issue with paragraph
-Streamline bold directive in sentence
> Fix broken images

- content/cloud-servers/checking-for-a-security-compromise-backdoors-and-intruders.md
Migrate checking-for-a-security-compromise-backdoors-and-intruders.md file to new platform.
> Migrate security compromise  article

- content/index.html
- content/rackspace-metrics/rackspace-metrics.md
- Add HTML tag back into product page.
> Rackspace Metrics layout issues

- content/index.html
Fixes https://github.com/rackerlabs/nexus-control/issues/335
> tweak row divs to get the metrics icon in the right spot

- content/rackspace-metrics/rackspace-metrics-faq.md
Intention is to get the collapsable list to work
> Add H3 level headers

- content/cloud-servers/updating-servicenet-routes-on-cloud-servers-created-before-june-3-2013.md
Migrate updating-servicenet-routes-on-cloud-servers-created-before-june-3-2013.md.
> Migrate servicenet routes pre june 2013 article

- content/cloud-servers/checking-for-a-security-compromise-backdoors-and-intruders.md
- content/cloud-servers/checking-for-a-security-compromise-rescue-mode-investigation.md
> apply editorial feedback

- content/cloud-databases/cloud-databases-faq.md
- content/cloud-databases/permissions-matrix-for-cloud-databases.md
- content/cloud-images/creating-an-ubuntu-1310-image-for-the-rackspace-open-cloud.md
- content/cloud-images/identifying-rackspace-standard-images.md
- content/cloud-images/sharing-images-in-the-cloud-control-panel.md
- content/cloud-monitoring/detailed-permissions-matrix-for-rackspace-monitoring.md
- content/cloud-networks/permissions-matrix-for-cloud-networks.md
- content/cloud-queues/permissions-matrix-for-cloud-queues.md
- content/cloud-servers/cloud-servers-faq.md
- content/cloud-servers/detailed-permissions-matrix-for-dns.md
- content/cloud-servers/using-python-novaclient-to-manage-scheduled-images.md
- content/cloud-servers/using-task-states-with-server-imaging.md
- content/cloud-sites/cloud-sites.md
- content/cloud-sites/getting-started-with-cloud-sites-logging-into-the-control-panel.md
- content/cloud-sites/self-migrating-a-mysql-4-database-to-mysql-5.md
- content/general/definition-of-personally-identifiable-information-pii.md
- content/managed-operations/managed-operations-faq.md
- content/rackconnect/using-onmetal-cloud-servers-with-rackconnect-v20.md
- content/rackspace-auto-scale/permissions-matrix-for-auto-scale.md
- content/rpc-openstack/rackspace-private-cloud-software-package-update-20-march-2013.md
Change KC references to How-To in the articles.
> Kc to howto#516

- content/exchange/microsoft-exchange-public-folders.md
- content/exchange/public-folder-permissions-for-exchange.md
- content/exchange/working-with-public-folders-through-outlook-for-exchange-2007-and-2010.md
As per issue #393 I've pulled out the public folder permissions table into it's own article and changed the two articles that reference it to include a link instead of the actual table of information.
> Permissions article#393

- content/exchange/upgrading-to-exchange-2013.md
- content/exchange/upgrading-to-exchange-2016.md
With advisement from Deanna Husting, this fixes #391
> Clarify exchange#391

- content/cloud-databases/database-replication-with-cloud-databases.md
Changes are as follows:
- Added a small section to point out that the same functions are available via the API and provide a link to that area
- added small clarification that the monitoring variables for replication are on the replica instance
- Added a monitoring example for seconds_behind_master
> Small additions and corrections to replica how-to

- content/rackspace-metrics/use-annotation-metrics.md
Reverts rackerlabs/rackspace-how-to#562
> Revert "Fix image reference and modify image sizes."

- content/index.html
- products.csv
> Change "cloud monitoring" to "rackspace monitoring" in config files.

- content/rackspace-monitoring/rackspace-monitoring-faq.md
-Fix several style typos for consistency.
-Change all question headers to H4
> Change title to "Rackspace Monitoring FAQ"

- content/index.html
> Link directly to infrastructure user guide

- content/managed-operations/cloud-servers-with-managed-operations-support-for-windows.md
fixes #590 
Fixed the table layout so the header row was aligned correctly. Also fixed Active Directory table where three rows were added on to the previous row, creating extra columns.
> fix table columns to line up correctly

- content/cloud-servers/first-generation-to-next-generation-cloud-server-migration-faq.md
- content/cloud-servers/installing-xenserver-tools-on-next-generation-windows-cloud-servers.md
> Add mention of Window's server XenServer tools

- content/cloud-servers/installing-xenserver-tools-on-next-generation-windows-cloud-servers.md
> Incorporate Kelly's edits for XenServer article

- content/cloud-backup/update-the-rackspace-cloud-backup-agent.md
> wrong yum syntax

- content/cloud-backup/best-practices-for-cloud-backup.md
- content/cloud-backup/rackspace-cloud-backup-create-a-backup.md
- content/cloud-backup/rackspace-cloud-backup-overview.md
- Fix **Warning** formatting.
- Add an extra sentence to complete the warning.
> Edits to backup symlink warnings

- content/cloud-servers/install-ssl-certificates-on-windows-server-2008r2-and-2012.md
Silly markdown is so specific about these kinds of things. Trying to fix the formatting of a nested ordered list.
> increasing indent to fix formatting of nested list

- content/cloud-servers/introduction-to-iptables.md
> Add Zoltan's change to a branch.

- content/cloud-dns/managed-dns-faq.md
**Do not publish before 3/14**
Create Managed DNS FAQ article that needs to publish between 8am-9am on Monday morning (3/14/2016).
Nicole Hairston will okay the article before publish.
> Create Managed DNS FAQ  (3/14 PUBLISH DATE)

- content/exchange/microsoft-exchange-cloud-office-control-panel-overview.md
fixes #404 
Updates to the screenshots and available options in the Cloud Office Control panel via Beau Bailey
> update screenshots and info to reflect office control panel changes

- PULL_REQUEST_TEMPLATE.md
**Warning:** Before creating a pull request, make sure that you are submitting your change on a **BRANCH** instead of a fork. You can review how to make a branch in the [contribution guidelines](https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md) for this repository. 
Ensure that your change conforms to Rackspace styles and standards by reviewing the checklist below. Only review the items on the checklist that apply to your change. For detailed descriptions of each checklist item, see the [style guidelines](https://github.com/rackerlabs/rackspace-how-to/blob/master/style-guidelines.md) for this repository. 
After you have used the checklist to review your change, please describe the changes you made in the bulleted list below. Use present tense. For example, if you …
> Change "warning" to "stop"

- content/exchange/adding-microsoft-exchange-mailboxes.md
- content/exchange/microsoft-exchange-cloud-office-control-panel-overview.md
- content/rackspace-email/add-rackspace-email-mailboxes.md
**!!!STOP!!!** 
Before creating a pull request, make sure that you are submitting your change on a **BRANCH** instead of a fork. 
You can review how to make a branch in the **contribution guidelines**(https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md) for this repository. 
Ensure that your change conforms to Rackspace styles and standards by reviewing the checklist below. Only review the items on the checklist that apply to your change. For detailed descriptions of each checklist item, see the [style guidelines](https://github.com/rackerlabs/rackspace-how-to/blob/master/style-guidelines.md) for this repository. 
After you have used the checklist to review your change, please describe the changes you made in the bulleted list below. Use present tense. For example, …
> Edit link text

- PULL_REQUEST_TEMPLATE.md
**!!!STOP!!!** 
Before creating a pull request, make sure that you are submitting your change on a **BRANCH** instead of a fork. 
You can review how to make a branch in the **contribution guidelines**(https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md) for this repository. 
Ensure that your change conforms to Rackspace styles and standards by reviewing the checklist below. Only review the items on the checklist that apply to your change. For detailed descriptions of each checklist item, see the [style guidelines](https://github.com/rackerlabs/rackspace-how-to/blob/master/style-guidelines.md) for this repository. 
After you have used the checklist to review your change, please describe the changes you made in the bulleted list below. Use present tense. For example, …
> Create shorter version of pull request template

- content/cloud-files/cloud-files-faq.md
!!!STOP!!!
Before creating a pull request, make sure that you are submitting your change on a **BRANCH** instead of a fork. 
You can review how to make a branch in the **contribution guidelines**(https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md) for this repository. 
Please describe the changes you made in the bulleted list below. Use present tense. For example, if you added a question about image backups to the Cloud Images FAQ, you would say, "Add question about image backups to FAQ."
- 
- 
- 
**DO NOT MERGE YOUR OWN PULL REQUEST**
> Apply Kelly's edits to the eventual consistency question in the Cloud Files FAQ

- content/rackspace-monitoring/pillars-of-the-rackspace-monitoring-solution
!!!STOP!!!
Before creating a pull request, make sure that you are submitting your change on a **BRANCH** instead of a fork. 
You can review how to make a branch in the **contribution guidelines**(https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md) for this repository. 
Please describe the changes you made in the bulleted list below. Use present tense. For example, if you added a question about image backups to the Cloud Images FAQ, you would say, "Add question about image backups to FAQ."
- 
- 
- 
**DO NOT MERGE YOUR OWN PULL REQUEST**
Remove extraneous marks from metadata.
> Update Pillars of Rackspace Monitoring article

- PULL_REQUEST_TEMPLATE.md
!!!STOP!!!
Before creating a pull request, make sure that you are submitting your change on a **BRANCH** instead of a fork. You can review how to make a branch in the **contribution guidelines**(https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md) for this repository. 
Please describe the changes you made in the bulleted list below. Use present tense. For example, if you added a question about image backups to the Cloud Images FAQ, you would say, "Add question about image backups to FAQ."
- Copy edited the content of this message. 
- 
- 
**DO NOT MERGE YOUR OWN PULL REQUEST**
> Suggest some copy edits to text

- content/cloud-backup/cloud-backup-faq.md
- content/cloud-backup/cloud-backup.md
- content/cloud-backup/generating-your-encrypted-key-in-cloud-backup.md
- content/cloud-backup/rackspace-cloud-backup-backup-actions.md
- content/cloud-backup/rackspace-cloud-backup-create-a-backup.md
- content/cloud-backup/rackspace-cloud-backup-overview.md
- content/cloud-backup/rackspace-cloud-backup-view-backup-information.md
!!!STOP!!!
- This is part of #416 and standardizes article titles for Cloud Backup, plus updating link text as necessary. Filenames were NOT changed.
-
- 
> Fix backup titles

- content/cloud-servers/set-up-apache-virtual-hosts-on-ubuntu.md
- Add the following missing tag to the vhost file example per customer reported issue: </VirtualHost>
> Add end tag to vhost file example

- content/cloud-block-storage/attach-a-cloud-block-storage-volume-to-an-onmetal-server-through-the-cloud-control-panel.md
!!!STOP!!!
- Remove \ from numbered steps.
- Fix code block underneath numbered steps
- 
> Attach a block storage formatting issue.

- content/cloud-block-storage/attach-a-cloud-block-storage-volume-to-an-onmetal-server-through-the-cloud-control-panel.md
!!!STOP!!!
- Remove $ signs from code blocks
-
- 
> Fix code blocks

- content/managed-operations/upgrade-to-managed-operations-service-level.md
> Remove devops references.

- content/managed-operations/managed-cloud-service-levels-faq.md
> Remove the “What is DevOps Automation” section.

- content/cloud-backup/index.md
!!!STOP!!!
- fixes #647 
- remove links to internal anchors
- 
> remove links to internal anchors

- content/cloud-backup/rackspace-cloud-backup-create-a-backup.md
-  Link to article returns 404.  Removed -0 from permalink.
> Remove -0 from permalink

- README.md
Add a clickable badge that takes you to the Strider build.
> Add a Strider build badge

- content/general/getting-started-with-role-based-access-control-rbac.md
Update the Permalink to remove the 0.  Link to article gets page-not-found.
> Remove the 0 from the permalink

- content/cloud-backup/generating-your-encrypted-key-in-cloud-backup.md
- content/cloud-backup/rackspace-cloud-backup-view-backup-information.md
- content/cloud-big-data/deploying-rackspace-cloud-big-data.md
- content/cloud-big-data/getting-data-into-your-big-data-cluster.md
!!!STOP!!!
- fixes #678 
- Change permalinks back to what they were before I edited the titles.
- 
> change permalinks back so the links wont be broken anymore

- content/cloud-dns/create-a-reverse-dns-record.md
!!!STOP!!!
- Removed -0 from permalink.
-
- 
> Change permalink to reflect file name.

- content/cloud-servers/using-ntp-to-sync-time.md
!!!STOP!!!
- Address issue #589 
- Added security section
- Needs edits from @kmsholcomb 
> Add ntp security section

- content/cloud-servers/linux-server-security-best-practices.md
> Modify layout for stanard How-To layout.

- CONTRIBUTING.md
- Add section called "Getting started with GitHub".
- Add forking steps in "Create an article" section.
- Add forking steps to "Edit an article" section.
- Add section about editing a PR.
> Added forking instructions to Contributing.md

- content/cloud-big-data/deploying-rackspace-cloud-big-data.md
> Remove unneeded image of Active status.

- content/cloud-databases/connect-to-a-cloud-database-with-a-fqdn-address-via-mysql-workbench.md
Removed 4 images:  
- % asset_path cloud-databases/connect-to-a-cloud-database-with-a-fqdn-address-via-mysql-workbench/1.png %     
- % asset_path cloud-databases/connect-to-a-cloud-database-with-a-fqdn-address-via-mysql-workbench/2.png %     
- % asset_path cloud-databases/connect-to-a-cloud-database-with-a-fqdn-address-via-mysql-workbench/3.png 
- % asset_path cloud-databases/connect-to-a-cloud-database-with-a-fqdn-address-via-mysql-workbench/5.png %
> Remove unneeded images and adjust verbiage.

- content/cloud-sites/test-php-smtp-functionality.md
Looks like there needs to be an extra hard return after a bulleted list before the code block will format properly (so 2 hard returns total).
> fix code block formatting

- content/cloud-sites/test-php-smtp-functionality.md
Still can't get this code to format properly using the triple backtick method, so I'm switching to indenting to see if that works.
> change to indent instead of triple backticks for code blocks

- content/cloud-backup/cloud-backup-troubleshooting.md
Fixes #726
Apply Kelly's feedback to clarify article.
> apply editor feedback

- CONTRIBUTING.md
- content/cloud-dns/changing-dns-settings-on-linux.md
- content/cloud-dns/creating-dns-records-with-cloud-dns.md
- content/cloud-dns/using-dig-to-query-nameservers.md
- content/cloud-dns/what-is-an-soa-record.md
- content/cloud-networks/set-up-apache2-web-server-on-two-instances-with-shared-ip.md
Adjust certain DNS article titles to conform to style guide.  Other DNS article titles were reviewed but not changed, intentionally.
> Fixdnstitles

- CONTRIBUTING.md
- content/cloud-images/creating-a-centos-65-image-for-the-rackspace-open-cloud.md
- content/cloud-images/creating-an-ubuntu-1310-image-for-the-rackspace-open-cloud.md
- content/cloud-images/transferring-images-between-regions-of-the-rackspace-open-cloud.md
- content/cloud-networks/set-up-apache2-web-server-on-two-instances-with-shared-ip.md
Fixed certain images article titles to confirm with style guide.  Others left unchanged, intentionally.
> Fiximagestitles

- content/cloud-databases/cloud-databases-faq.md
Need to hold off on this PR till April 19th
> Revert "Adding new versions and new volume size"

- content/cloud-servers/rescue-mode-on-windows-servers.md
> Update image reference with html reference

- content/cloud-servers/rescue-mode-on-windows-servers.md
> Fix formatting issue with numbered lists

- content/rackspace-intelligence/rackspace-intelligence-faq.md
Fixes #407 
Update response to question about Rackspace Intelligence availability for cloud and dedicated accounts.
> update response about cloud vs dedicated accounts

- content/cloud-images/cloud-images-faq.md
- content/cloud-images/creating-a-centos-65-image-for-the-rackspace-open-cloud.md
- content/cloud-images/creating-an-ubuntu-1310-image-for-the-rackspace-open-cloud.md
- content/cloud-images/detailed-permissions-matrix-for-cloud-images.md
- content/cloud-images/identifying-rackspace-standard-images.md
- content/cloud-images/index.md
Part of #705 
First half of the Cloud Images content review
> Images content edit 1

- content/cloud-files/use-swiftly-to-upload-an-image.md
- content/cloud-images/preparing-an-image-for-import-into-the-rackspace-opencloud.md
- content/cloud-images/rackspace-standard-and-non-standard-images.md
- content/cloud-images/sharing-images-in-the-cloud-control-panel.md
- content/cloud-images/transferring-images-between-regions-of-the-rackspace-open-cloud.md
- content/cloud-images/use-swiftly-to-download-an-exported-image.md
Part of #705 
Final part of Cloud Images review
> Images content edit 2

- content/rackconnect/access-the-rackconnect-management-interface.md
- content/rackconnect/accessing-rackconnect-cloud-servers.md
- content/rackconnect/features-introduced-in-rackconnect-v20.md
- content/rackconnect/getting-rackconnect-support.md
- content/rackconnect/introducing-rackconnect-v20.md
- content/rackconnect/managing-rackconnect-v20-network-policies.md
- content/rackconnect/rackconnect-key-terms.md
- content/rackconnect/rackconnect-v20-requirements.md
- content/rackconnect/rackconnect-v20.md
This is the first set of RackConnect articles that I am cleaning up for issue https://github.com/rackerlabs/rackspace-how-to/issues/705. The changes are very minimal. Please review, revise, and merge at will.
> Copy edit RackConnect articles

- content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md
- Fix several grammatical errors and typos
- Clarify restart in step 8.
> Add more of Luke's edits

- content/rpc-openstack/installing-and-testing-cinder-in-your-rackspace-private-cloud-lab-environment.md
- content/sharepoint/getting-started-with-rackspace-services-for-sharepoint.md
- content/sharepoint/how-to-install-the-rackspace-cloud-storage-app-for-microsoft-sharepoint.md
- content/skype-for-business/working-with-audio-and-voice-calls-in-hosted-skype-for-business.md
Adjusted tiles, where needed to conform with the title formation standards.
> Fix titles for Skype, Sharepoint and RPC-OS

- content/rackspace-monitoring/creating-a-monitoring-check-using-the-cloud-control-panel.md
- content/rackspace-monitoring/getting-started-with-rackspace-monitoring-cli.md
- content/rackspace-monitoring/introducing-rackspace-monitoring-on-mobile-devices.md
- content/rackspace-monitoring/monitoring-differences-between-rackspace-server-users-and-non-rackspace-server-users.md
- content/rackspace-monitoring/monitoring-network-traffic.md
- content/rackspace-monitoring/troubleshooting-the-rackspace-monitoring-agent.md
Need to conform better to title standards.
> Update Monitoring article titles

- content/rackspace-auto-scale/how-auto-scale-cooldowns-work.md
- content/rackspace-cdn/what-is-a-cdn.md
Need to better conform to tile formation standards.
> Modify article title for CDN and Autoscale

- content/rackconnect/getting-started-with-the-rackconnect-v30-api.md
- content/rackconnect/using-cloud-load-balancers-with-rackconnect.md
Need to better conform to title standards.
> Fix titles for Rackconnect articles

- content/general/managing-role-based-access-control-rbac.md
- content/general/overview-role-based-access-control-rbac.md
- content/general/what-is-managed-colocation-from-rackspace.md
- content/general/when-am-i-billed-for-my-account.md
- content/general/when-is-managed-colocation-a-good-fit.md
- content/general/why-do-you-need-my-vat-id-number.md
We need to need to update some titles to better conform to standards.
> Fix General article titles

- content/exchange/accessing-the-full-version-of-migrationwiz.md
- content/exchange/adding-a-microsoft-exchange-contact.md
- content/exchange/adding-microsoft-exchange-mailboxes.md
- content/exchange/deleting-and-resending-blackberry-service-books-bes.md
- content/exchange/migrating-exchange-to-exchange-via-outlook.md
- content/exchange/migrating-public-folder-data.md
- content/exchange/using-outlook-cached-mode-with-rackspace-hosted-exchange.md
- content/exchange/working-with-public-folders-through-outlook-for-exchange-2007-and-2010.md
We need to comply with standards.
> Fix Exchange article titles

- content/rackspace-intelligence/creating-custom-graphs-of-activity-in-rackspace-intelligence.md
- content/rackspace-intelligence/logging-in-to-the-rackspace-intelligence-dashboard.md
- content/rackspace-intelligence/monitoring-entities-with-rackspace-intelligence.md
- content/rackspace-intelligence/monitoring-open-alerts-with-rackspace-intelligence.md
- content/rackspace-intelligence/setting-up-a-database-to-work-with-rackspace-intelligence.md
- content/rackspace-intelligence/viewing-and-creating-graphs-of-activity-in-rackspace-intelligence-for-dedicated-accounts.md
- content/rackspace-intelligence/viewing-basic-graphs-of-activity-in-rackspace-intelligence.md
- content/rackspace-intelligence/working-with-alarms-checks-entities-notifications-and-notification-plans-in-rackspace.md
- content/rackspace-intelligence/working-with-alarms.md
- content/rackspace-intelligence/working-with-checks.md
- content/rackspace-intelligence/working-with-notification-suppressions-in-rackspace-intelligence.md
- content/rackspace-intelligence/working-with-notifications-in-rackspace-intelligence.md
- content/rackspace-intelligence/working-with-rackspace-intelligence-notification-plans.md
We need to conform to title standards.
> Fix Intelligence article titles

- content/cloud-sites/am-i-charged-bandwidth-for-uploading-data-to-or-from-my-cloud-sites-account.md
- content/cloud-sites/checking-bandwidth-usage-for-cloud-sites.md
- content/cloud-sites/controlling-access-to-linux-cloud-sites-based-on-the-client-ip-address.md
- content/cloud-sites/creating-a-simple-aspnet-site-for-the-main-cloud-sites-account.md
- content/cloud-sites/displaying-svg-images-in-cloud-sites-php-deployments.md
- content/cloud-sites/dns-management-how-to-update-your-ip-address.md
- content/cloud-sites/does-rackspace-support-frontpage-extensions.md
- content/cloud-sites/does-the-cloud-sites-ftp-service-support-restartscontinuations.md
- content/cloud-sites/does-the-rackspace-cloud-support-secure-email.md
- content/cloud-sites/enabling-raw-logging-for-a-cloud-sites-website.md
- content/cloud-sites/handling-an-invalidcastexception-using-sql-clr-data-types-on-cloud-sites.md
- content/cloud-sites/handling-high-traffic-events-on-cloud-sites.md
- content/cloud-sites/how-can-i-contact-the-cloud-sites-billing-team.md
- content/cloud-sites/installing-cakephp-on-cloud-sites.md
- content/cloud-sites/installing-gallery-on-cloud-sites.md
- content/cloud-sites/installing-oscommerce-on-cloud-sites.md
- content/cloud-sites/installing-serendipity-on-cloud-sites.md
- content/cloud-sites/installing-wordpress-on-cloud-sites.md
- content/cloud-sites/managing-cloud-sites-email-dns-records.md
- content/cloud-sites/migrating-mysql-50-to-51.md
- content/cloud-sites/my-php-script-is-not-working-what-should-i-do.md
- content/cloud-sites/purging-cloud-sites-webmail.md
- content/cloud-sites/recovering-from-and-dealing-with-a-site-compromise.md
- content/cloud-sites/self-migrating-a-mysql-4-database-to-mysql-5.md
- content/cloud-sites/sending-html-mail-via-php-in-cloud-sites.md
- content/cloud-sites/using-a-staging-url.md
- content/cloud-sites/using-cloud-databases-with-your-cloud-site.md
- content/cloud-sites/using-wp-supercache-to-optimize-wordpress-on-cloud-sites.md
Need to conform to title standards.
> Fix sites article titles

- content/rackspace-email/upgrade-email-hosting-cloud-office-control-panel.md
-Still looking for further clarification on statement, signed up online.
> Edits to Beau's Cloud Office Control Panel links

- content/rackspace-metrics/rackspace-metrics-faq.md
> Change permalink to reflect file name

- content/cloud-servers/first-gen-to-next-gen-cloud-servers-migration-pre-checks.md
- content/rackspace-monitoring/troubleshooting-the-rackspace-monitoring-agent.md
- Fixes merge conflict from Pr #861.
- Fix spelling errors.
> Kruzda xentools installer command fix

- content/cloud-servers/first-generation-to-next-generation-cloud-server-migration-faq.md
> Update Xen server link to point to new article

- content/rackspace-auto-scale/rackspace-auto-scale-control-panel-user-guide-introduction.md
> fix link to concepts article and formatting of links

- content/rackconnect/rackconnect-v30-upgrade-information.md
> update downtime for upgrade path b

- content/exchange/add-an-activesync-or-bes-license.md
- content/exchange/adding-microsoft-exchange-mailboxes.md
- content/exchange/deleting-and-resending-blackberry-service-books-bes.md
- content/exchange/exchange-email-mailbox-features.md
- content/exchange/exchange-faq.md
- content/exchange/index.md
- content/exchange/manually-configure-android-devices-for-email-hosted-on-exchange-2007.md
Part of #770 
These edits mostly clarify the Cloud Office CP rather than the Cloud CP.
> Update exchange cp refs

- content/cloud-sites/using-cloud-databases-with-your-cloud-site.md
Update text and update or remove images where no longer needed.
> Update verbiage and remove images

- content/exchange/manually-configure-entourage-ews-for-email-hosted-on-exchange-2007.md
- content/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2007.md
- content/exchange/manually-configure-mac-mail-for-email-hosted-on-exchange-2007.md
- content/exchange/manually-configure-mac-mail-for-email-hosted-on-exchange-2010.md
- content/sharepoint/upgrade-sharepoint-site-storage-cloud-office-control-panel.md
- content/skype-for-business/hosted-microsoft-lync-at-rackspace-deployment-guide.md
> Update exchange cp refs 2

- content/cloud-servers/centos-6-apache-and-php-install.md
Fixes #849 
Confirmed by myself and Angela B.
> Add php package to install command

- content/cloud-servers/are-cloud-servers-pci-dss-compliant.md
In response to email seeking old What is PCI Compliance? article.
> add information about pci dss and reorganize with headers

- content/cloud-sites/allow-or-block-specific-ip-addresses-from-accessing-your-cloud-sites-website.md
Updated to use Apache 2.4 ruleset, cleaned up some formatting and erroneous information from the old article.
> Updated for Apache 2.4 ruleset

- README.md
> Add ninja assignments to readme

- content/rackspace-monitoring/alarm-language-generic-thresholds-made-easy.md
Talked with Steve Ortiz about replacing the node_id field with the audit_date field. This is my first test before I do a sweeping change.
> Test replace node_id with audit_date

- content/rackspace-monitoring/available-checks-for-rackspace-monitoring.md
Talked with Steve Ortiz about replacing the node_id field with the audit_date field. This is my second test before I do a sweeping change.
> Test2 replace node_id with audit_date

- content/exchange/manage-distribution-lists-in-exchange.md
Changed "Managers" to "Members" as the "Managers" functionality is no longer an available function.
> Changed "Managers" to "Members"

- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation.md
> Add SERVICENETENABLED installation option

- content/general/use-pivot-tables-with-your-cloud-billing-invoice.md
I had a conversation internally about this
> csv export note added to the pivot tables article

- content/cloud-block-storage/cloud-block-storage-faq.md
Remove duplicate question in Security section at the end of the FAQ.
> Update cloud-block-storage-faq.md to remove duplicate question

- scripts/newfiles.sh
instructions include in body of scripts/newfiles.sh
> Add script to identify new files added between two dates.

- content/contribution-class/contribution-class-exercise.md
Completed the standalone training and exercise.
> Response to the Survey

- content/rackspace-auto-scale/rackspace-auto-scale-faq.md
Change FAQ question header levels to h4
> fix header levels

- content/rackspace-auto-scale/rackspace-auto-scale-control-panel-user-guide-concepts.md
fix link to create a scaling group article
> fix malformed link

- scripts/audits.sh
Add script that will allow H2 team to search for files that are due for a complete audit. The search relies on date ranges.
> Create audit script

- content/cloud-servers/apache-configuration-on-ubuntu.md
- content/cloud-servers/are-cloud-servers-pci-dss-compliant.md
- content/cloud-servers/backing-up-your-files-with-rsync.md
- content/cloud-servers/basic-cloud-server-security.md
> Servers content edit 2

- scripts/audits.sh
Removed "fi" from line 51. Had too many "fi"s.
> Edit the script so it works

- content/rackspace-intelligence/differences-between-rackspace-intelligence-for-cloud-accounts-and-dedicated-accounts.md
from: differences-between-rackspace-intelligence-for-cloud-accounts-and-dedicated-accounts/
to: differences-between-rackspace-intelligence-for-cloud-account-and-dedicated-account/
> Modify permalink

- content/cloud-servers/backing-up-your-files-with-rsync.md
Apply Kelly's feedback to Back up your files with rsync
> apply editor feedback to rsync article

- content/cloud-networks/floating-ip-faq
Add L3 sub-heading to allow  L4 questions.
> Add Sub-heading

- content/cloud-servers/application-and-load-testing-guidelines.md
> apply editor feedback to application load test article

- content/cloud-servers/connect-to-a-cloud-server.md
Test was successful. Restoring permalink.
> Restore permalink

- content/rackspace-metrics/use-annotation-metrics.md
- content/rackspace-metrics/use-enum-metrics.md
> Add permalink and audit_date fields

- content/cloud-servers/configure-flash-drives-in-high-io-instances-as-data-drives.md
> fix flash drives typo

- content/cloud-sites/getting-started-with-cloud-sites-configuring-ssl-on-your-websites.md
> Fixes to Hikarutilmitt pull request

- content/cloud-backup/rackspace-cloud-backup-backup-actions.md
Permalink value set to cloud-backup-actions/  instead of  cloud-backup-backup-actions.
> Fix permalink value

- style-guidelines.md
To account for the style guide's new organization
> fix links to style guides

- content/rackspace-monitoring/mobile-alerts-from-rackspace-monitoring.md
> Fix links to developer guide in article

- content/rackspace-monitoring/install-and-configure-the-rackspace-monitoring-agent.md
> fix links to monitoring guide

- content/cloud-sites/modify-your-hosts-file.md
> Update versions in modify your host article

- content/cloud-servers/common-windows-issues-key-management-server-activation.md
List each command separately. If used inline, they will not work.
> Update commands listed under step 7

- content/cloud-servers/common-windows-issues-key-management-server-activation.md
> Fix commands in step 4 and 5.

- content/cloud-databases/managing-backups-for-cloud-databases.md
> Edits to Steve's DB patch

- content/cloud-servers/common-windows-issues-key-management-server-activation.md
> Update post sync commands.

- content/cloud-databases/replicate-backup-for-disaster-recovery-with-cloud-databases.md
Added that each backup copy will be charged the same as the original backup
> Added pricing info for replicated backups

- content/cloud-databases/scheduled-backups-for-cloud-databases.md
Added:
- Pricing section that calls out how scheduled backups are priced
- details that backups are retained, even if the associated instances are deleted.
> Added retention and pricing information

- content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md
> Updates to branch Hdansou upgrade xentools

- content/cloud-databases/scheduled-backups-for-cloud-databases.md
- content/cloud-servers/about-cloud-server-images.md
> Patch for Colin's pull request

- content/cloud-sites/modify-your-hosts-file.md
- Fixes issue #1033 
- Fixes issue #903
> Editorial edits for "Modify Your hosts" 

- content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md
- Issue with code block becoming a single line
- Fix typo
> Attempt fix on code block issue in Xenserver article 

- content/cloud-dns/changing-dns-settings-on-linux.md
Add IAD information to Datacenter table.
> Add IAD namserver

- content/cloud-servers/install-epel-and-additional-repositories-on-centos-and-red-hat.md
> apply editor feedback, add audit_date

- content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md
> fixed formatting of the script output

- content/cloud-servers/checking-listening-ports-with-netstat.md
> Make small editorial edits to netsec article

- content/cloud-databases/database-replication-with-cloud-databases.md
> Remove images from database replication article

- content/cloud-databases/managing-cloud-databases-configuration-groups-in-the-cloud-control-panel.md
Remove un-needed images and adjust verbiage, as needed.
> Remove images from cloud-control-panel.md.

- content/cloud-databases/managing-cloud-databases-ha-groups-in-the-cloud-control-panel.md
- content/cloud-databases/managing-users-for-cloud-databases.md
- content/cloud-databases/monitoring-cloud-databases-in-the-cloud-control-panel.md
> Remove unneeded images 0613 1st round

- content/cloud-servers/mysql-resetting-a-lost-mysql-root-password.md
Update Reset a MySQL root password article.
> Update Reset a MySQL root password

- content/rpc-openstack/index.md
Added v12 links and updated broken links.
> Fixed RPC how-to landing page

- content/cloud-servers/generate-a-csr-with-openssl.md
> Change to Davisaaronj patch 2

- content/cloud-servers/rackspace-cloud-essentials-centos-configuring-a-user-in-vsftpd.md
> Fixes to Davisaaronj patch 3

- content/rpc-openstack/rackspace-private-cloud-spheres-of-support.md
- content/rpc-openstack/rpc-openstack-faq.md
> Change previous section header for RPC articles

- content/cloud-servers/generating-rsa-keys-with-ssh-puttygen.md
> Auditing article.

- content/cloud-sites/install-and-use-drupal-on-cloud-sites.md
- content/cloud-sites/install-and-use-joomla-on-cloud-sites.md
- content/cloud-sites/install-and-use-mojoportal.md
- content/cloud-sites/installing-wordpress-on-cloud-sites.md
Add step numbering to 3 articles.
> Cloud sites image pruning 160621 1

- content/cloud-backup/best-practices-for-cloud-backup.md
#1123 Update to include additional suggestion to test your restores.
> Update Backup Best Practices restore info

- content/cloud-servers/checking-linux-file-permissions-with-ls.md
> Updated for H2 audit

- content/cloud-servers/centos-6-apache-and-php-install.md
> How_to audit.

- content/rpc-openstack/rackspace-private-cloud-partner-devices.md
- content/rpc-openstack/rackspace-private-cloud-software-and-sosreport.md
- content/rpc-openstack/rackspace-private-cloud-software-vm-block-migration.md
Relates to #705 
Correct format issues in the following articles:
- Rackspace Private Cloud - Partner Devices
- Rackspace Private Cloud Software and sosreport
- Rackspace Private Cloud Software Package Update - 20 March 2013
- Rackspace Private Cloud Software - VM Block Migration
> Rpc image pruning 160624 1

- content/cloud-servers/generate-a-csr-with-openssl.md
> Applying Kelly edits.

- content/cloud-servers/installing-mysql-server-on-centos.md
> Kyle 160627 1

- content/cloud-servers/rackspace-cloud-essentials-centos-configuring-a-user-in-vsftpd.md
- content/cloud-servers/rackspace-cloud-essentials-centos-installing-vsftpd.md
> Kyle 160627 2

- content/cloud-servers/installing-mysql-server-on-centos.md
Remove mini TOC links. Discussed with Kelly and we are retaining the list for layout reference, but removing links.
> Remove TOC links.

- content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md
- Editorial changes to PR #1150
> Update Citrix Tools installation process

- content/cloud-dns/nslookup-checking-dns-records-on-windows.md
- content/cloud-servers/connecting-to-linux-from-windows-by-using-putty.md
> Kyle 160627 3

- README.md
> Add August Ninja assignments

- content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md
Changed wording about using cURL to obtain HTML5 console link.
Changed notice to RCv2 customers into a Warning dialogue due to high importance. 
Added heading for reset network.
> Minor changes to verbiage and layout

- content/cloud-servers/mysql-connect-to-your-database-remotely.md
> Apply edits to Connect to a MySQL DAtabase remotely article.

- content/cloud-dns/cloud-dns-faq.md
- content/cloud-dns/create-dns-records-for-cloud-servers-with-the-control-panel.md
- content/cloud-dns/using-dig-to-query-nameservers.md
- content/cloud-servers/cloud-servers-faq.md
- content/cloud-servers/rackspace-cloud-essentials-transferring-your-domain-to-be-served-from-rackspace-cloud.md
- content/cloud-servers/rackspace-cloud-essentials-what-are-your-name-servers.md
- content/cloud-servers/rackspace-name-servers.md
- content/cloud-servers/serving-your-domain-from-a-rackspace-cloud-server.md
- content/cloud-sites/getting-started-with-cloud-sites-rackspace-nameservers-and-creating-custom-nameservers.md
- content/cloud-sites/net-45-in-cloud-sites.md
- content/cloud-sites/using-a-staging-url.md
It has come to my attention that there is a better way to address the issue #524, than the method that I originally intended. 
Moving any new details to issue #1169
> Revert "Replace DNS endpoints with new defaults"

- content/cloud-servers/installing-mysql-server-on-centos.md
Had a merge conflict in an earlier PR and missed the conflicted metadata. This fixes it.
> fix metadata that i missed in merge conflict

- content/cloud-servers/connecting-to-linux-from-windows-by-using-putty.md
Should take care of the strider error
> add single quotes to date in metadata

- products.csv
- Fixes issue #1182 
In order to reflect the metadata contained within Autoscale articles
> Change Auto Scale product name

- content/rackspace-auto-scale/all.md
> Update product name to reflect metadata of article

- content/cloud-servers/installing-mysql-server-on-centos.md
Looking at this article to compare with "Install MySQL Server on Ubuntu" and noticed that the article begins with an unnecessary "Overview" heading. So, I deleted it!
> Delete unnecessary "Overview" heading

- content/cloud-servers/installing-mysql-server-on-ubuntu.md
Fixes #1177 
Applied edits to Install MySQL Server on Ubuntu article.
> Edit Install MySQL Server on Ubnutu article

- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows.md
> Update Cloud Backup article to include new info for agents v2

- content/cloud-block-storage/create-and-attach-a-cloud-block-storage-volume.md
> Update article - change Servers to Storage in steps

- content/cloud-sites/cloud-sites-subaccounts.md
> Convert to Getting Started article and update permalink

- CONTRIBUTING.md
Make several minor edits.
@kmsholcomb Can you take a look at these minor changes when you have time?
> Edit Contributing.md

- content/rackspace-metrics/index.md
> fix the link text.  

- content/cloud-backup/update-the-rackspace-cloud-backup-agent.md
See the issue for his updates.
> Fixes #1228 - minor updates from SME Brett Johnson

- content/rackspace-metrics/integrate-statsd-with-rackspace-metrics.md
> Change permalink to reflect article title

- content/cloud-networks/cloud-networks-faq.md
- content/rpc-openstack/installing-and-testing-cinder-in-your-rackspace-private-cloud-lab-environment.md
> Fix in the future references 160714 1

- content/cloud-servers/checking-listening-ports-with-netstat.md
- Fixes issue #913 (SME review of article)
> Add SME notes to netstat article

- content/rackspace-metrics/index.md
Fix the link that was broken by https://github.com/rackerlabs/rackspace-how-to/pull/1234
> Fix link to statsd

- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation.md
by using silent installation - changes from SME, Brett Johnson
> Fixes #1227 Cloud Backup article Install the agent on Windows

- Understanding the cloud computing stack: SaaS, Paas, IaaS
Relates to #906 
Convert from white-paper at https://8026b2e3760e2433679c-fffceaebb8c6ee053c935e8915a3fbe7.ssl.cf2.rackcdn.com/whitepaper_pdf/Understanding-the-Cloud-Computing-Stack.pdf and redirect.
> Create Understanding the cloud computing stack: SaaS, Paas, IaaS

- content/cloud-servers/what-is-new-with-onmetal-cloud-servers.md
- content/cloud-sites/information-for-ms-sql-changes.md
> Update in the future references 160715 1

- content/cloud-backup/best-practices-for-backing-up-your-data-cloud-block-storage-versus-cloud-backup.md
> Updated note in encryption section to a warning and add text

- content/rackspace-email/rackspace-email-and-hosted-exchange-settings.md
> apply editor feedback and add audit_date

- content/cloud-backup/cloud-backup-troubleshooting.md
Fixes #1239 Updates from Brett Johnson
> Fixes #1239 - update the Cloud Backup troubleshooting article

- content/cloud-files/migrating-from-parse-to-rackspace.md
> Change all directory paths to code blocks

- content/cloud-backup/rackspace-cloud-backup-backing-up-databases.md
Fixes #1259 - Updates from SME, Brett Johnson.
> Fixes #1259 article update for Back up databases with Cloud Backup

- README.md
Adding me to Ninja schedule for this week.
> Update ninja schedule

- README.md
Just adding myself to the support schedule
> add myself to ninja duty

- content/rpc-microsoft/architecture-requirements-for-rackspace-private-cloud-powered-by-microsoft.md
The table was just a copy and paste of the Web Site Cloud section. Updated to accurately reflect the one wiki site: https://one.rackspace.com/display/mpc/Cloud+Platform+Powered+By+Rackspace+-+Product+Line+Architecture+Requirements
> Updated the Cloud Platform "Base Cloud" table

- content/rackspace-metrics/integrate-statsd-with-rackspace-metrics.md
> Edit "wolfdancers" external contribution

- content/cloud-networks/removing-networks-from-a-cloud-server.md
> Fix typo from isolaged to isolated

- content/cloud-networks/cloud-networks-faq.md
Apply SME findings recevied post-publishing.
> Apply feedback.

- content/general/overview-role-based-access-control-rbac.md
> Update in the future refs 160727 1

- content/cloud-servers/open-ports-in-the-linux-firewall-to-access-pop-and-imap-mail-servers.md
-Relates to #1292 
This PR is only to correct the numbering before sending request to SMEs.
> Correct layout for numbering issue

- content/cloud-sites/migrate-a-mysql-51-database-to-mariadb-10-on-cloud-sites.md
Adjusted text for MAriaDB to show 10.1
Clarified a statement about using mysqldump
adjusted text regarding future DFW versions, since that migration has been completed for some time.
Will add screenshots later.
> Updates to new version

- content/cloud-servers/open-ports-in-the-linux-firewall-to-access-pop-and-imap-mail-servers.md
> Incorporate Editor edits and SME updates

- content/rpc-openstack/index.md
- content/rpc-openstack/rackspace-private-cloud-documentation.md
- Fixes #1309 
Update links in the following articles for v12:
- Rackspace Private Cloud Documentation
- Rackspace Private Cloud Powered by OpenStack
> Update rpc openstack version reference 160802

- content/general/rackspace-billing-faq.md
Relates to #1203 
Adding audit_date to this.
> Add audit_date

- content/cloud-sites/migrate-a-mysql-51-database-to-mariadb-10-on-cloud-sites.md
removed line about migrations not being forced, since we are, indeed, forcing them in September
> removed a bad item

- content/general/overview-role-based-access-control-rbac.md
> Add earlier note of unavailable products on RBAC

- CONTRIBUTING.md
It's the easiest way to contribute so let's highlight it.
> Highlight the Edit This Article button

- content/managed-operations/using-the-myrackspace-firewall-manager.md
> Modify image.

- content/rackconnect/Add authorized users in the RackConnect Management Interface.md
> Update Add authorized users in the RackConnect

- content/cloud-servers/cloud-servers-faq.md
> Add additional Plesk add cPanel information in cloud servers FAQ

- content/cloud-databases/high-availability-for-cloud-databases.md
A bunch of small updates to the page:
- amount of time for the failover process was inconsistent in the document
- Clarified some wording on failovers
- Added and clarified some of the bullets in the limitations section
> Various updates and tweaks to the HA how-to

- content/cloud-databases/index.md
- reworked the "managing an instance" section to list some newer docs
- changed the pricing link
> Putting more recent docs up top, updating links

- content/cloud-servers/cloud-servers-faq.md
Reverts rackerlabs/rackspace-how-to#1349
> Revert "Add additional Plesk add cPanel information in cloud servers FAQ"

- content/rpc-openstack/index.md
> Fix broken link

- content/cloud-servers/cloud-servers-faq.md
This is to re-apply the changes to the Cloud Servers FAQ.
> Adjust the verbiage for Plesk and cPanel in Cloud Servers FAQ

- content/cloud-networks/set-up-apache2-web-server-on-two-instances-with-shared-ip.md
don't know why this didn't apply to original PR, but here it is again.
> Shared IP Article awaiting stakeholder review.

- content/cloud-networks/cloud-networks-faq.md
Add Shared IP FAQs to Networks FAQ page
Fixes #1328
> add shared ip faqs

- content/cloud-servers/migrate-to-rackspace-from-another-hosting-provider.md
Adding some additional information as suggested by Jason Hammons
Fixes #1322
> add additional information as per sme request

- content/cloud-servers/multi-factor-authentication-from-the-myrackspace-portal.md
> Resubmit article

- content/cloud-servers/multi-factor-authentication-from-the-myrackspace-portal.md
> Apply SME review feedback

- content/contribution-class/contribution-class-exercise.md
Reverts rackerlabs/rackspace-how-to#1398
We are reverting this pull request because merging your own PR is a violation of this repository.
> Revert "Update contribution-class-exercise.md"

- content/contribution-class/contribution-class-exercise.md
- Answered questions to ensure completion of pull request
> Answer questions

- content/cloud-networks/cloud-networks-faq.md
> Add updates to cloud networks faq

- content/cloud-orchestration/building-cloud-orchestration-templates.md
- content/cloud-orchestration/index.md
PR separate from initial merge to prevent conflict
> Change filename and permalink to reflect title

- content/exchange/accessing-the-full-version-of-migrationwiz.md
> Update link in Migration Wiz article

- content/cloud-orchestration/building-cloud-orchestration-templates.md
Incorporating some internal feedback from this article.
> Fix formatting on Building Cloud Orchestration templates article

- content/cloud-servers/installing-active-directory-domain-services-on-windows-server-2008-r2-enterprise-64-bit.md
> Update heading to read Enable Remote Management

- content/cloud-servers/managing-my-server.md
- content/cloud-servers/permissions-matrix-for-first-generation-cloud-servers.md
- content/cloud-servers/permissions-matrix-for-role-based-access-control-rbac.md
- content/cloud-servers/reset-your-server-password.md
- content/general/getting-started-with-role-based-access-control-rbac.md
- content/general/managing-role-based-access-control-rbac.md
- content/general/overview-role-based-access-control-rbac.md
- content/general/rackspace-account-invoice.md
- content/rackconnect/how-to-programmatically-determine-the-rackconnect-v20-automation-status-of-your-cloud.md
- content/rackconnect/rackconnect-faq.md
- content/rackconnect/rackconnect-v30-limitations.md
More first generation reference deletions.
> Remove first gen references 160912

- content/exchange/manually-configure-android-devices-for-email-hosted-on-exchange-2013.md
> apply suggestions from sme

- content/exchange/manually-configure-android-devices-for-email-hosted-on-exchange-2013.md
> apply editor feedback and adjust spacing in numbered list

- content/general/article-retired
Small edit to commit without the extraneous RS How-To directory.
> Modify article reitred page layout

- content/rackspace-metrics/integrate-carbon-deamon-with-rackspace-metrics.md
Missing permalink made article not viewable.
> add permalink to metadata

- content/cloud-databases/scheduled-backups-for-cloud-databases.md
- content/cloud-servers/speed-up-rsync-when-migrating-a-linux-server-from-the-command-line.md
> Steve's updates to scheduled backup article

- content/cloud-block-storage/detach-and-delete-cloud-block-storage-volumes.md
The subparagraph in the numbered list was also off with spacing, so the list was still broken.
> update Pr 1472

- content/cloud-databases/manage-cloud-databases-ha-groups-in-the-cloud-control-panel.md
> Fix _asset path for article

- content/cloud-block-storage/prepare-your-cloud-block-storage-volume.md
> Add unmount steps for Cloud Block Storage on  Linux and Windows servers.

- content/cloud-block-storage/index.md
Reverts rackerlabs/rackspace-how-to#1484
> Revert "Test section links with standard html"

- content/rackspace-cdn/rackspace-cdn-secure-delivery-options.md
> remove unsupported cert

- content/cloud-servers/installing-active-directory-domain-services-on-windows-server-2008-r2-enterprise-64-bit.md
- Relates to #1431
Applied edits submitted by Kelly.
> Apply edits

- content/cloud-servers/how-to-serve-multiple-domains-using-virtual-hosts.md
- content/cloud-servers/serve-multiple-domains-using-virtual-hosts.md
> Incorporate Kelly's edits into Multiple Domains article

- content/cloud-servers/installing-active-directory-domain-services-on-windows-server-2008-r2-enterprise-64-bit.md
> add audit date

- content/exchange/index.md
> fix links to point at articles instead of control panel

- content/cloud-files/protect-your-cloud-files-cdn-bill-from-unexpected-usage.md
> Remove a line

- content/cloud-servers/design-and-build-cloud-servers-for-stability.md
> Change link

- content/cloud-servers/design-and-build-cloud-servers-for-stability.md
- content/cloud-servers/mapping-of-amazon-web-services-resources-to-rackspace-resources.md
> How-To Marketplace audit

- content/cloud-load-balancers/permissions-matrix-for-cloud-load-balancers.md
> Fix CLB matrix table formatting

- content/general/article-retired.md
> Remove + symbols in metadata

- content/general/comparison-of-dedicated-and-cloud-hosting.md
This is not monitoring related, actually.
> Fixed the link to the right place

- content/cloud-servers/mysql-connect-to-your-database-remotely.md
> Fix build error from Ben's PR

- content/rackspace-monitoring/available-checks-for-rackspace-monitoring.md
clarified that cloud control panel contains the common checks and added reference to Rackspace Intelligence.
> clarification on availability of monitoring checks

- content/rackspace-email/rackspace-email-control-panel-overview.md
Fixes #1540 
Part of Cloud Office Control Panel Project
> remove outdated cp options

- content/cloud-servers/checking-running-services-on-linux.md
> Add SME notes for Linux article

- content/rpc-openstack/index.md
ready to go. Closes issue #1513
> Add release v13 to RPC

- content/rackspace-cdn/access-rackspace-cdn.md
- content/rackspace-cdn/add-and-manage-domains-in-rackspace-cdn.md
- content/rackspace-cdn/cdn-enable-amazon-s3-buckets-and-accelerate-your-website-with-rackspace-cdn.md
- content/rackspace-cdn/change-dns-to-enable-rackspace-cdn.md
- content/rackspace-cdn/create-a-rackspace-cdn-service.md
- content/rackspace-cdn/create-and-manage-caching-rules-in-rackspace-cdn.md
- content/rackspace-cdn/create-and-manage-restrictions-in-rackspace-cdn.md
- content/rackspace-cdn/delete-a-rackspace-cdn-service.md
- content/rackspace-cdn/features-of-rackspace-cdn.md
- content/rackspace-cdn/permission-matrix-for-rackspace-cdn.md
- content/rackspace-cdn/rackspace-cdn-edge-rules.md
- content/rackspace-cdn/rackspace-cdn-faq.md
- content/rackspace-cdn/rackspace-cdn-geography-mapping.md
- content/rackspace-cdn/rackspace-cdn-secure-delivery-options.md
- content/rackspace-cdn/refresh-content-in-a-rackspace-cdn-service.md
- content/rackspace-cdn/work-with-origins-and-origin-rules-in-rackspace-cdn.md
- Fixes issue #1444 
Adding audit dates to articles updated by Catherine and reviewed by Kelly. Mark Barta assures me these articles contain up to date information.
> Add audit dates to audited CDN articles

- content/rackspace-monitoring/rackspace-monitoring-checks-and-alarms.md
Fixed the links to API doc.  Added missing content for agent checks and hostinfo checks.
> fixed links and added missing content

- content/cloud-servers/installing-an-ssl-certificate-on-apache.md
> Edit external contribution "Cleanup certificate uploading instructions"

- content/cloud-images/cloud-image-creation-format-and-process.md
On Cloud Image creation and process
Closes issue #1546
> Add article for Reese

- content/cloud-networks/common-network-troubleshooting-tools.md
> Fix link at bottom of the page

- CONTRIBUTING.md
> Add Youtube version on Contribution Class

- content/rpc-microsoft/architecture-requirements-for-rackspace-private-cloud-powered-by-microsoft.md
- content/rpc-microsoft/rpc-microsoft-faq.md
Editing the How-to article following the Style Guidelines for contributing
content:
* Spacing and formatting
* Clarify pronouns
* Sentence and word order
closes rackerlabs/rackspace-how-to/issues/#1531
> [Audit] Architecture reqs for RPC powered by MS

- content/cloud-servers/objectrocket-documentation.md
- Fixes part of issue #1520  
- Replace any outdated links that had obvious equivalents 
- Outdated links that do not have obvious equivalents have not been updated.
> Update Object Rocket doc article

- content/rpc-microsoft/architecture-requirements-for-rackspace-private-cloud-powered-by-microsoft.md
- content/rpc-microsoft/rpc-microsoft-faq.md
* Adding remaining edits to the Requirements chapter, and to
the FAQ chapter.
Closes issue /rackspace-how-to/issues/#1527
> [Audit] RPC powered by MS Edits

- content/cloud-servers/checking-for-a-security-compromise-backdoors-and-intruders.md
> Fix link in security article

- content/cloud-servers/create-an-inbound-port-allow-rule-for-windows-firewall-2008.md
> Fix numbered list in firewall article

- content/cloud-orchestration/quick-set-up-with-rackspace-cloud-orchestration.md
> Full audit of article.

- content/rpc-openstack/rackspace-private-cloud-documentation.md
> Update RPC article to point to rpc docs

- content/index.md
> [WIP] Adding a tab for dedicated hosting

- products.csv
> Add dedicated hosting to products.csv

- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows.md
Code blocks not formatting correctly.
Not related to an issue
> Fix code blocks at the end of Backup article

- content/dedicated-hosting/add-new-vpn-user-myrackspace-portal.md
I'm so dumb! I copy/pasted the img code, and forgot to remove the width/height tags. No wonder this image has been so wonky.
> remove width and height tags in image

- content/cloud-servers/windows-server-security-best-practices.md
The article is still relevant but needed minor updates.
> windows-server-security-best-practices update

- content/cloud-orchestration/deploy-wordpress-packages-by-using-rackspace-cloud-orchestration.md
Updating the How To steps after reviewing the menus and
options available in mycloud.
Addresses Issue rackerlabs/rackspace-how-to/issues/#1575
> [Audit] Updates to deploying wordpress with orchestration

- content/cloud-servers/prepare-to-migrate-a-windows-server.md
- Fixes issue #1532
- Fix link at the top
> Audit windows migration article

- content/cloud-servers/permissions-matrix-for-role-based-access-control-rbac.md
- content/rackspace-auto-scale/permissions-matrix-for-auto-scale.md
Fixes #1599 
Setting new standards to apply to all RBAC permissions matrix articles. This is the master article, but I'll include one other product-specific article as well for reference.
> Rbac overhaul

- content/managed-operations/cloud-servers-with-managed-operations-support-for-linux.md
- Part of issue #1613 
- Add Ubuntu 16.04 to Managed Ops list.
> Full audit: Managed ops on Linux

- content/cloud-servers/windows-server-security-best-practices.md
> Add editorial feedback for security article

- content/rpc-openstack/rpc-openstack-faq.md
> Remove version-specific references

- content/cloud-servers/glusterfs-high-availability-through-ctdb.md
> delete unnecessary step and update reference links

- content/cloud-files/permissions-matrix-for-cloud-files.md
> permissions matrix for cloud files update

- content/rackspace-auto-scale/permissions-matrix-for-auto-scale.md
applied editor feedback from servers rbac article, and matching language of API methods to API reference
> update auto scale rbac article

- content/cloud-files/permissions-matrix-for-cloud-files.md
Matched the method name, API action, and description to what was in the API reference guide.
@kmsholcomb Here's another one to double-check :)
> apply feedback and match method language to API reference

- content/rackspace-email/email-access-options-during-an-email-migration.md
> incorporate sme edits

- content/retired-articles/use-enum-metrics.md
> delete enum metrics article and move to retired folder

- content/cloud-dns/detailed-permissions-matrix-for-dns.md
RBAC Matrix update to match new template. Ref: #1639 
Fixes #1639
> Update to permission matrix for cloud DNS, ref: Issue 1639

- content/cloud-images/detailed-permissions-matrix-for-cloud-images.md
- content/cloud-servers/permissions-matrix-for-next-generation-cloud-servers.md
> Kelly edits for server/images RBAC

- content/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2013.md
> Add Cory's edits to public folders article

- content/rpc-openstack/index.md
RPC Admin Guide archived per
https://github.com/rackerlabs/docs-rpc/pull/804
> Remove RPC Admin Guide references

- article-templates/task-based-article-template.md
Add folder for templates and task-based template
> add template for task-based articles

- content/rackconnect/rackconnect-v30-compatibility.md
> update note about onmetal v2 server compatibility

- content/contribution-class/contribution-class-exercise.md
* The training video asked!
* Ye shall receive!
> Add answer options for Sean Laszakovits

- content/rackspace-metrics/create-a-grafana-dashboard-for-rackspace-metrics.md
Based on user suggestion, added link to the steps for setting up Grafana manually.
> Added link to manual steps of setting up Grafana

- content/rpc-openstack/security-for-rackspace-private-cloud-powered-by-openstack.md
fixing typos and HTML before sending to SME. See #1661 for issue details.
Fixes #1661
> Full audit, ref issue #1661

- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-linux.md
> attempting to fix list spacing

- content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-linux.md
> trying again to fix spacing

- content/rackspace-metrics/use-annotation-metrics.md
Fixed the link to API doc.  Consolidated general product information.
> technical review

- content/rackspace-metrics/rackspace-metrics-overview.md
- Updated the link to blog post to the how-to article since the latter is more up-to-date
- Fixed another link to the API Doc
> fixed links

- content/rackspace-metrics/rackspace-metrics-overview.md
two small errors (one syntax, the other style) noted while working on another PR
> Syntax fix

- content/cloud-big-data/detailed-permissions-matrix-for-cloud-big-data-v2.md
proofed before SME review
Fixes #1706
> [WIP] Full Audit, ref issue #1706

- content/cloud-block-storage/cloud-block-storage-overview.md
> Fix broken link in CBS overview article

- content/cloud-servers/reboot-your-server.md
minor update to text per SME.
Fixes #1733
> Update to cloud server reboot article per #1733

- content/cloud-databases/permissions-matrix-for-cloud-databases.md
- Fixes issue #1620 
-Change table to RBAC standard
> [WIP] Full audit: RBAC permissions matrix for Cloud Databases

- content/cloud-networks/troubleshooting-an-offline-website.md
Fixes issue #1750.
- Fix links
- Fix code blocks
> Fix links in common network article

- content/cloud-databases/permissions-matrix-for-cloud-databases.md
showed up as an error on a recent strider build; changing the acutes to single quotes
> fixing syntax

- CONTRIBUTING.md
> fixing email address

- content/exchange/public-folder-permissions-for-exchange-2007-and-2010.md
> Change public folder article title for technical accuracy
