content/cloud-block-storage/permissions-matrix-for-cloud-block-storage.md
Fixes #1685 
update formatting and match API method language to API reference guide
=> Full audit for CBS permission matrix

content/retired-articles/synchronizing-files-to-cloud-files-with-fileconveyor.md
=> comment out metadata, move article to retired-articles folder

content/rackspace-email/view-invoice-history-cloud-office-control-panel.md
fixes #1729 
@kmsholcomb can you give this a look?
=> apply sme updates

content/rackspace-intelligence/monitoring-entities-with-rackspace-intelligence.md
Also added mentioning of Dedicated device.
=> minor correction to match the product name

content/managed-operations/linux-patching-for-cloud-servers-managed-operations-service-level.md
proofing run before SME review.
Fixes #1666
=> [WIP] Full Audit, ref issue #1666

content/cloud-servers/mapping-of-amazon-web-services-resources-to-rackspace-resources.md
Fixing typo found by an enterprise user back in October that they never submitted here; the PR on the old KC repo (the KC everything one) is number 1.
=> Fixing typo

content/dedicated-hosting/Net-Device-Reboot-Button-FAQ.md
Created Net Device Reboot Button FAQ page
=> Created Net Device Reboot Button FAQ page

content/rackspace-cdn/index.md
=> Remove HTML from CDN index

content/cloud-backup/index.md, content/cloud-big-data/index.md, content/cloud-block-storage/index.md, content/cloud-databases/index.md, content/cloud-files/index.md, content/cloud-images/index.md, content/cloud-load-balancers/index.md, content/cloud-queues/index.md, content/cloud-servers/index.md, content/cloud-sites/index.md, content/exchange/index.md, content/managed-vmware-services/index.md, content/office-365/index.md, content/rackconnect/index.md, content/rackconnect/rackconnect-release-notes.md, content/rackspace-auto-scale/index.md, content/rackspace-email-archiving/index.md, content/rackspace-email/index.md, content/rackspace-intelligence/index.md, content/rackspace-metrics/index.md, content/rackspace-monitoring/index.md, content/rpc-openstack/rackspace-private-cloud-documentation.md, content/sharepoint/index.md, content/skype-for-business/index.md
fixing list formatting
Fixes #1780
=> Fixing index.md syntax

CONTRIBUTING.md
adding a note at the top about public vs enterprise GitHub. 
Fixes #1767
=> CONTRIBUTING.md update

content/cloud-orchestration/how-to-scale-multinode-wordpress-by-using-rackspace-orchestration.md
proofed before SME review
Fixes #1577
=> [WIP] Full Audit, ref issue #1577

content/rackspace-cdn/permission-matrix-for-rackspace-cdn.md
Fixes #1772 
Update formatting to match standard and API reference
=> [WIP] full audit cdn permissions matrix

content/cloud-orchestration/permissions-matrix-for-cloud-orchestration.md
Fixes #1768 
Update formatting to match standard
=> [WIP] full audit rbac orchestration

content/cloud-backup/permissions-matrix-for-cloud-backup.md
Fixes #1787 
Create permissions matrix for Cloud Backup.
=> [WIP] create permissions matrix for cloud backup

content/rackspace-monitoring/rackspace-monitoring-faq.md
=> Fix developer links in monitoring API

content/rackspace-monitoring/install-and-configure-the-rackspace-monitoring-agent.md
This is based on feedback from support looking for information on what systems does the agent support exactly.
=> updated with information on platform support

content/cloud-servers/migrate-from-parse-to-rackspace.md, content/cloud-servers/migrating-from-parse-to-rackspace.md
=> Edits to Chris Hutlin's patch

content/cloud-servers/supported-operating-systems.md
=> Add missing word "date"

content/cloud-block-storage/detach-and-delete-cloud-block-storage-volumes.md
Ref request from community in attached issue.
Fixes #1746
=> [WIP] Update to detach/delete block storage volumes article

content/cloud-servers/design-and-build-cloud-servers-for-stability.md
Add Loadview-Testing.com to the section for Load Testing
=> Design & Build Cloud Servers For Stability Update

content/rackspace-monitoring/detailed-permissions-matrix-for-rackspace-monitoring.md
Added reference to the complete list and removed the duplication.
=> clarification on checks

content/rackspace-email/cloud-office-control-panel.md
- Fixes issue #1731 
- Change table to bulleted list
- Remove images
=> Fix Cloud Office Control Panel links

content/cloud-networks/permissions-matrix-for-cloud-networks.md
Fixes #1782 
update formatting to match standard
=> [WIP] full audit rbac cloud networks

content/retired-articles/RETIRING-CONTENT.md
updating content to include alternative retire through atom, JSON validation.
Fixes #1821
=> [WIP] JSON Validation Info

content/rackspace-monitoring/rackspace-monitoring-checks-and-alarms.md
Also sorted the DCs by the name.
=> added missing DCs for recommended monitoring zone

content/cloud-queues/permissions-matrix-for-cloud-queues.md
=> [WIP] Full audit of Cloud Queues RBAC matrix

content/cloud-servers/view-and-reset-your-api-key.md
=> Update instructions on how to view a cloud API key.  Fixes #1844.

content/cloud-databases/importing-data-into-cloud-databases.md
=> [WIP] Full Audit on Importing Cloud Databases article

content/rackspace-monitoring/detailed-permissions-matrix-for-rackspace-monitoring.md
- Fix issue #1707 
SME review already implemented with PR #1810.
=> [WIP] Monitoring RBAC matrix audit

content/cloud-load-balancers/permissions-matrix-for-cloud-load-balancers.md
Checking against API.
Fixes #1783
=> [WIP] RBAC Full Audit on Cloud Load Balancers

content/managed-operations/managed-cloud-service-level-pricing.md, content/managed-operations/managed-cloud-service-levels-faq.md, content/retired-articles/managed-cloud-service-level-pricing.md
=> Review of Managed Ops Pricing article

content/cloud-servers/application-and-load-testing-guidelines.md
Fixes issue #1876 
offer an alternative for those who are not developers so-to-speak
=> alternative option

content/cloud-networks/vyatta-vrouter-add-a-local-administrative-user.md, content/cloud-servers/managing-my-server.md, content/cloud-servers/start-a-console-session.md, content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md, content/cloud-servers/what-is-new-with-onmetal-cloud-servers.md
Fixes #1798 
Full audits for all the articles included in this PR will be added to the backlog.
=> Replace "connect via console" with "emergency"

content/rackspace-cdn/configure-w3-total-cache-for-origin-pull-rackspace-cdn.md
Apply editor feedback and add audit date
Part of #1578
=> Full audit w3tc and CDN

content/rackspace-email/rackspace-email-password-recovery-faq.md
=> Add update number instructions for Webmail FAQ

content/cloud-images/creating-an-ubuntu-1310-image-for-the-rackspace-open-cloud.md, content/cloud-images/index.md
https://support.rackspace.com/how-to/creating-an-ubuntu-1310-image-for-the-rackspace-open-cloud/
=> Full audit: Creating an Ubuntu image for the RS open cloud (Images)

content/exchange/upgrading-to-exchange-2016.md
=> Correct bad hyperlinks per Deanna Husting

content/general/detailed-permissions-matrix-for-billing-services.md
=> Full audit: Permissions for billing services

content/cloud-images/transferring-images-between-regions-of-the-rackspace-open-cloud-with-pitchfork.md
I was answering a ticket and was told that I should share the steps on the community articles - I started this and realized this may not be the channel for community articles but I'm not sure how to do that. I poked around on the new how-to and community portals but figured I had come to far to give up so I should stash it on github and make someone on the KB article team aware of it. 
<3,
Mo Nash
@ESC_monash in our internal IRC channels, if you want to hit me up during the day
I'm @momothehobo in slack - See ya! :D
fixes #1877
=> transferring-images-between-regions-of-the-rackspace-open-cloud-with-pitchfork

content/rackspace-email-archiving/index.md
fixes #1875 
updated the link to go to the proper article, and also fixed the permalink format
=> update link to enable email archiving

article-templates/concept-based-article-template.md, article-templates/task-based-article-template.md, article-templates/troubleshooting-article-template.md
Add additional templates for new articles
=> add troubleshooting and concept article templates

CONTRIBUTING.md
update contributing guidelines to include information about using templates
=> add info about templates

content/managed-operations/managed-cloud-service-levels-faq.md
updating and fixing rebase
Fixes #1665
=> [WIP] Rebased for issue #1665

content/cloud-servers/hidden-base-images.md
Fixes #1857 
Add additional hidden images from SME.
@kmsholcomb when you get back, can you add this to your editing queue?
=> [WIP] Hidden base images audit

content/cloud-servers/view-and-reset-your-api-key.md
Partially fixes https://github.com/rackerlabs/docs-rackspace/issues/282
Reference ticket:
https://encore.rackspace.com/ticketing/account/10040922/ticket/170313-dfw-0001270
From the encore ticket:
You can view the API key by clicking on your username in the upper right > My Profile & Settings > Scroll down to 'Security Settings', the last line will have 'Rackspace API Key' and click 'Show' to view.
=> Update article to reflect current Control Panel

content/cloud-servers/about-regions.md
=> Full Audit - Issue 1813

content/rpc-openstack/rpc-openstack-faq.md
Fixes https://github.com/rackerlabs/docs-rpc/issues/996
=> Remove Solutions Template section from FAQ

content/rpc-openstack/rpc-openstack-faq.md
Under What devices are certified for RPC compute nodes?
=> Add Ubuntu Server 16.04 LTS to RPC FAQ 

_includes/all-articles-list.html
Figured this one out
Ref old PR #1812
Fixes rackerlabs/docs-workstream#198
=> fixing alphabetical sort of all articles lists

content/dedicated-hosting/firewall-manager-v2-access-list-rules.md, content/dedicated-hosting/firewall-manager-v2-access-list-theory-and-best-practices.md
New article from #1934 with editor feedback applied
=> Fwmv2 access list theory

content/rackspace-monitoring/rackspace-monitoring-checks-and-alarms.md
Based on the recent latency analysis, we have updated the recommended monitoring zones
=> updated the recommended monitoring zones

content/cloud-servers/install-epel-and-additional-repositories-on-centos-and-red-hat.md
EL5 is almost EOL and the documentation should not to include information for this EOL OS.
=> IUS eol el5

content/dedicated-hosting/network-device-reboot-faq.md
=> Update "created_by" field on network-device-reboot-faq.md

content/retired-articles/adding-a-mobile-sync-license.md
=> retire adding a mobile sync license

content/cloud-servers/hidden-base-images.md
=> add centos image to list

content/cloud-databases/backup-your-mysql-database-with-phpmyadmin.md, content/cloud-dns/como-modificar-mi-archivo-de-hosts.md, content/cloud-dns/como-modifico-meus-arquivos-de-hosts.md, content/cloud-dns/modify-your-hosts-file.md, content/general/cms-comparison-drupal-joomla-and-wordpress.md, content/general/update-an-existing-ssl-certificate.md, content/rackspace-email/test-and-send-mail-using-php.md
=> Move cloud sites articles

content/rackspace-email/manage-user-spam-settings-for-rackspace-email.md
=> Add info to spam settings article

content/retired-articles/rackconnect-release-notes.md
fixes #1789 
Redirect: https://github.com/rackerlabs/nexus-control/pull/709
=> retire rackconnect release notes

content/retired-articles/configuring-a-software-raid-on-a-linux-general-purpose-cloud-server.md
=> Retire RAID article

content/rpc-openstack/index.md
=> RPC v14 General Availability

content/rpc-openstack/rpc-openstack-faq.md
=> Full Audit: RPC FAQ

content/microsoft-azure/index.md
and using it to test github/strider's PR payload problem
=> fixing a note and testing the strider build at the same time

content/cloud-databases/access-slow-query-and-general-logs-for-cloud-databases.md
=> update information about log queries that dont use index

content/managed-operations/sitecore-cloud-portals-and-account-management.md
- Information about MyRackspace portal changed for technical accuracy.
- Add note about how Sitecore manages billing
=> Republish Sitecore portals article to How-To

content/managed-operations/deploy-to-sitecore-cloud-using-ftp.md, content/managed-operations/deploy-to-sitecore-cloud.md
=> New article: Deploy to Sitecore using FTP

style-guidelines.md
Tested one link and anchor fix before fixing all of them
=> Tested one link and anchor fix

content/index.md
=> Remove User Guide link at top of How-To page

content/index.md
=> Move RPC to top of How-To landing page

content/retired-articles/cloud-office-control-panel.md
=> Retire redundant Cloud Office CP article

content/rackspace-email/rackspace-directory-sync-install-and-configure.md
https://github.com/rackerlabs/rackspace-how-to/edit/master/content/rackspace-email/rackspace-directory-sync-install-and-configure.md is the article link
=> Please Update Article

content/cloud-servers/permissions-matrix-for-role-based-access-control-rbac.md, content/general/detailed-permissions-matrix-for-support-tickets.md
Please do not merge this now, we will be merging this change in few weeks once Reach UI is done with their changes.
=> New article: RBAC for ticketing [MERGE MAY 16]

content/general/cms-comparison-drupal-joomla-and-wordpress.md
=> Removed caching sites links.

content/cloud-servers/hidden-base-images.md
=> add new hidden base images for ubuntu

content/retired-articles/cloud-server-name-transitions.md
=> Retire Server Name Transition article

content/general/dfw1-data-center-migration-customer-faq.md
Add unsearchable article about DFW1 migration.
=> Ccl issue 2041

content/contribution-class/contribution-class-exercise.md
changes are made as part of an exercise
=> Add my replies

content/rackspace-email/troubleshoot-email-delivery.md
=> fix typo in article

content/cloud-servers/mapping-of-amazon-web-services-resources-to-rackspace-resources.md, content/cloud-servers/permissions-matrix-for-role-based-access-control-rbac.md, content/cloud-servers/rackspace-open-cloud-reference-architecture.md, content/general/overview-role-based-access-control-rbac.md, content/general/support.md, content/managed-operations/cloud-server-configuration-options.md, content/managed-operations/cloud-servers-with-managed-operations-support-for-windows.md, content/managed-operations/index.md, content/managed-operations/managed-operations-faq.md
=> update or remove mailgun references

content/cloud-files/configuring-rackspace-cloud-files-with-cyberduck.md, content/cloud-servers/multi-factor-authentication-from-the-cloud-control-panel.md, content/cloud-servers/using-onmetal-cloud-servers-through-api.md, content/general/change-account-information.md, content/general/rackspace-billing-faq.md, content/general/viewing-and-editing-user-information-for-your-account.md, content/retired-articles/configure-cloud-feeds-archiving-in-the-cloud-control-panel.md
=> edit references to account settings in cp

content/rackspace-email/rackspace-email-faq.md
=> Fixed recipient limit

content/retired-articles/updating-servicenet-routes-on-cloud-servers-created-before-june-3-2013.md
=> retire servicenet article for old cloud servers

content/cloud-backup/install-or-update-the-cloud-backup-agent-on-linux.md
=> Reverse first 2 steps in section titled "Install the agent on Arch, Gentoo, and SUSE systems"

content/rackspace-email/add-rackspace-email-mailboxes.md
I'm experimenting with how formatting bulleted lists affects white spacing in between them.
=> Fix bulleted spacing in email article

content/cloud-servers/updating-servicenet-routes-on-cloud-servers-created-before-june-3-2013.md
Some support teams heavily use this article and wanted it to be republished.
=> bring back servicenet article

content/managed-operations/sitecore-cloud-faq.md
=> New article: Sitecore FAQ

content/cloud-servers/cloud-feeds-overview.md
=> remove reference to feeds in cp

content/cloud-backup/install-or-update-the-cloud-backup-agent-on-linux.md
Per #backup channel instructions from Brett Johnson.
=> Update apihost to show both US and UK values for <apiDrvesrvr>

content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows.md
Requested by Brett Johnson in #backup Slack channel
=> Update to show US and UK values for api drivesrvr for ApiHostName

content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation.md
=> Add additional info about data center being the same as region

content/general/introduction-to-mailgun-email-automation.md
=> move mailgun article to general folder

content/exchange/set-up-microsoft-exchange-email-forwarding.md
=> Fix formatting errors.

content/general/sign-up-for-racksapce-services.md
=> New article: Sign Up for Rackspace Services 

content/exchange/recover-a-deleted-microsoft-exchange-mailbox.md
=> Recover a deleted microsoft exchange mailbox

content/rackspace-email/rackspace-webmail.md
Link: https://github.com/rackerlabs/rackspace-how-to/blob/master/content/rackspace-email/rackspace-webmail.md
=> Update Article Please

content/contribution-class/contribution-class-exercise.md
Add my responses to the survey
=> Add my responses to the survey

content/office-365/index.md, content/office-365/set-up-office-365.md
- Also includes changes to the Office 365 introduction page
=> New article: Set up office 365

content/office-365/add-a-domain-in-office-365.md
=> Add domain in office 365 article 

content/office-365/index.md, content/office-365/office-365-faq.md
Don't if this is causing the problems with side navigation
=> Fix Office 365 index page metadata

content/office-365/add-a-domain-in-office-365.md
Change the word 'uuse' to 'use'
=> Correct a typo

content/exchange/change-a-mailbox-password-for-microsoft-exchange.md
I have also sent an email with these Screen Captures.
=> Password reset exchange

content/general/use-pivot-tables-with-your-cloud-billing-invoice.md
=> update according to SME

content/rackspace-email/email-migration-services.md
Made some revisions to this article.
=> Revise email migration services

content/rackspace-email/cloud-office-migrations-faq.md
I would like to place question, answers in expandable boxes if possible.
=> Cloud office migrations FAQ article revisions

content/rackspace-email/migrate-your-email-by-using-the-self-service-migration-tool.md
=> Self migration tool revision

content/cloud-servers/transferring-your-dns-hosting-to-rackspace.md
Closes issue #2144 
Kelly please edit for me!
=> Update/audit DNS hosting transfer article

content/general/use-pivot-tables-with-your-cloud-billing-invoice.md
=> add instructions for opening csv in utf-8

content/cloud-servers/hidden-base-images.md
Fedora 24 hit EOL and adding it to hidden list
=> Add Fedora 24

content/rackspace-intelligence/working-with-checks.md
Discovered these while writing the new article about custom dashboards.
=> Full Audit: Working with Checks

content/cloud-block-storage/cloud-block-storage-faq.md, content/retired-articles/about-volume-types.md
=> add volume info to faq and retire article

content/rackspace-intelligence/working-with-alarms.md
As suggested by Kelly in PR #2186
=> Full Audit: Working with Alarms

content/cloud-block-storage/cloud-block-storage-quotas.md
=> Full audit cbs quotas

content/managed-operations/sitecore-managed-cloud-premium-faq.md
Change from Sitecore Cloud to Sitecore Managed Cloud Premium.
=> Change name of Sitecore product to correct name

content/rackspace-email/index.md
=> Rse landing page

content/managed-operations/sitecore-managed-cloud-topologies.md, content/managed-operations/sitecore-managedcloud-topologies.md, content/managed-operations/update-sitecore-cloud-license.md
submitting 2 articles, update a license, Sitecore Managed Cloud Topologies document
=> adding 2 articles

content/cloud-servers/keep-a-cloud-server-up-to-date.md, content/cloud-servers/keep-cloud-serves-up-to-date.md
=> New Article: Keep a cloud server up to date

content/FAWS/using-putty-to-access-private-instances.md
- Fixes issue #1880  
Content taken from PR #1861
=> FAWS: New article: Access a private RDS instance with Putty

content/managed-operations/oracle-business-intelligence-12c-release-new-features.md
=> INFODEV-450 TriCore: Convert and add article for OBIEE 12c Data Blending, Mashup, and XSA

content/rackspace-email/add-domains-with-the-cloud-office-control-panel.md
Fixing formatting issues so that the nameservers are correct for copy/paste
=> Fix formatting issue

content/cloud-servers/cloud-servers-faq.md
=> fix bad link format

content/managed-operations/oracle-business-intelligence-enterprise-edition-tips.md
=> INFODEV-447 TriCore: Convert and add article for Oracle Business Intelligence Enterprise Edition tips

content/dedicated-hosting/add-new-vpn-user-myrackspace-portal.md
=> Fix wording on dedicated article

content/cloud-servers/provisioning-cloud-resources-when-migrating-from-amazon-web-services.md
=> remove outdated info and minor edits

content/general/dns-fundamentals.md
Moving from whitepapers site to How-To
=> add dns fundamentals

content/rackconnect/using-cloud-load-balancers-with-rackconnect.md
Added verbiage for how to get RackConnect v3 working with cloud load balancers.
=> RackConnect v3 does work with CLB

content/rackconnect/rackconnect-v30-compatibility.md
Added verbiage for RCv3 with Cloud Load Balancers
=> RackConnect v3 works with Cloud Load Balancers

content/general/email-fundamentals.md
add Email fundamentals with contents links
=> add email fundamentals

content/general/dns-fundamentals.md
add list of content links to dna fundamentals
=> add content list dns fundamentals

content/cloud-orchestration/deploy-wordpress-packages-by-using-rackspace-cloud-orchestration.md
=> minor edits and audit date update

content/rackspace-email/spam-filtering.md
=> full audit spam filtering

content/managed-operations/cloud-servers-with-managed-operations-support-for-windows.md
=> Update the Active Directory section

content/general/detailed-invoices-overview.md
infodev-660
update instructions and minor edits
=> full audit detailed invoice overview

content/cloud-networks/configuring-interface-based-firewall-on-the-vyatta-network-appliance.md
=> fix article title typo

content/dedicated-hosting/network-device-reboot-faq.md
referenced the schedule reboot article
=> Urgent! Updated single line. corrected out of date info

content/rackconnect/rackconnect-v30-upgrade-information.md
RCv3 does work with Cloud Load Balancers and OnMetal 2.0
=> Removed outdated information

content/general/rackspace-mitigations-against-cpu-speculative-execution-vulnerabilities.md
=> update cpu vulnerabilities article

content/rackspace-email/email-issue-on-tmobile-android-phones.md, content/rackspace-email/outgoing-email-issue-on-android-phones.md
The problem affects receiving email, not just sending, so that was clarified, among other things.  Also, a typo (SPN->APN) was fixed.
=> Clarify the problem and its temp resolution

content/rackspace-email/view-and-pay-unpaid-invoices-cloud-office-control-panel.md
=> BCP - view-and-pay-unpaid-invoices-cloud-office-control-panel

content/sharepoint/upgrade-sharepoint-site-storage-cloud-office-control-panel.md
=> BCP - upgrade-sharepoint-site-storage-cloud-office-control-panel

content/vmware-services/vmware-server-virt-faq.md
Temporary fix until the VMware team gets back to us.
=> Fix managed VMware services FAQ side nav

content/cloud-servers/start-a-console-session.md
Hey @cyrichardson can you take a pass at this? It looked pretty good to me, but you might see something that I missed.
=> full audit start a console session

content/general/use-pivot-tables-with-your-cloud-billing-invoice.md
=> BCP use-pivot-tables-with-your-cloud-billing-invoice

content/general/rackspace-billing-faq.md
=> BCP - rackspace-billing-faq

content/general/combine-invoices-for-rackspace-managed-and-cloud-accounts.md
=> BCP - combine-invoices-for-rackspace-managed-and-cloud-accounts

content/general/faq-role-based-access-control-rbac.md
Initial commit to create PR. PLACEHOLDER ONLY. Please do not merge.
=> BCP-update-faq-role-based-access-control-rbac: INFODEV-909

content/retired-articles/detailed-invoices-overview.md
See https://github.com/rackerlabs/nexus-control/pull/830 for redirect.
=> Retire article. 

content/cloud-backup/install-or-update-the-cloud-backup-agent-on-linux.md
originally from brett-johnson.  Pulled into this PR with my changes so it could be in a branch instead of direct to master.
=> updates to cbu linux deb

content/cloud-block-storage/create-a-clone-of-a-cloud-block-storage-volume.md, content/cloud-block-storage/create-and-use-cloud-block-storage-snapshots.md, content/cloud-servers/are-cloud-servers-pci-dss-compliant.md, content/cloud-servers/getting-started-with-cloud-servers.md, content/general/definition-of-personally-identifiable-information-pii.md, content/general/encryption-fundamentals.md
=> remove whitepaper references

content/index.md, content/rpc-vmware/all.md, content/rpc-vmware/index.md, content/rpc-vmware/vmware-rpcv-faq.md, products.csv
separate RPC-VMware from Managed VMware Services product
=> split vmware products

content/general/overview-role-based-access-control-rbac.md
Initial commit to create PR. PLACEHOLDER ONLY. Please do not merge.
=> BCP-update-overview-role-based-access-control-rbac: INFODEV-911

content/cloud-images/transferring-images-between-regions-of-the-rackspace-open-cloud-with-pitchfork.md
Don't want customer to get all the way thru the article only to find they can't import ;)
=> Adding caveats

content/index.md, content/vmware-services/all.md, content/vmware-services/index.md, content/vmware-services/vmware-server-virt-faq.md, products.csv
change Managed VMware Services to VMware Server Virtualization
=> change vmware services name

content/managed-operations/managed-operations-faq.md
fixes #2509 
hollandbackup.org does not support https.
=> Change dead link and convert http to https link

content/managed-operations/managed-operations-faq.md
Took a closer look at this after Charles Stocker fixed all the links and found a couple of places where spaces were needed.
=> Add spaces

content/rackspace-cdn/rackspace-cdn-secure-delivery-options.md
Added:
DigiCert Global Root G2
To the list of approved CAs
=> Added newly added approved CA

content/dedicated-hosting/firewall-manager-v2.md
- Remove outdated image.
- Small editorial change
=> Small tweaks to Firewall Manager V2 main page

content/cloud-servers/installing-mysql-server-on-ubuntu.md
=> full audit install mysql on ubuntu

scripts/audits.sh, scripts/no_audits.sh
=> Add script that finds files without audit dates: INFODEV-1265

scripts/audits.sh
=> Filter out files we don't need to check: INFODEV-1274

content/general/rackspace-account-invoice.md
Initial commit to create PR. PLACEHOLDER ONLY. Please do not merge.
=> BCP-update-rackspace-account-invoice: INFODEV-910

content/managed-operations/sitecore-cloud-portals-and-account-management.md
=> updated article to reflect proper timing

content/vmware-services/index.md
I accidentally committed a fake test to master :P please help
=> Undoing my fake test - oops

content/rackconnect/accessing-rackconnect-cloud-servers.md
=> Applied SME edits

content/cloud-networks/common-network-troubleshooting-tools.md
to identify windows versus other default tools
=> Updated default tools section

content/general/viewing-and-editing-user-information-for-your-account.md
full audit for card INFODEV-1394
=> update instructions to reflect changes in cp eyebrow

content/general/cms-comparison-drupal-joomla-and-wordpress.md
update links to installation forums
=> full audit cms comparison

content/index.md, content/retired-articles/sharepoint/all.md, content/retired-articles/sharepoint/getting-started-with-rackspace-services-for-sharepoint.md, content/retired-articles/sharepoint/how-to-install-the-rackspace-cloud-storage-app-for-microsoft-sharepoint.md, content/retired-articles/sharepoint/index.md, content/retired-articles/sharepoint/sharepoint-faq.md, content/retired-articles/sharepoint/upgrade-sharepoint-site-storage-cloud-office-control-panel.md, products.csv
=> Retire Sharepoint.

content/general/update-an-existing-ssl-certificate.md
=> Rewrite to make generic linux

content/dedicated-hosting/schedule-net-device-reboot.md
added one sentence to account for an issue we had with a negative customer experience
=> Fast update - one sentence

content/general/change-to-new-primary-contact.md
Based on SME feedback received from Jackie
=> Small tweak to primary contact article

content/retired-articles/determine-if-your-server-is-a-first-generation-cloud-server.md, content/retired-articles/first-gen-to-next-gen-cloud-servers-migration-pre-checks.md, content/retired-articles/first-generation-cloud-servers-sample-code.md, content/retired-articles/first-generation-end-of-life-migrations.md, content/retired-articles/first-generation-to-next-generation-cloud-server-migration-faq.md
JIRA 1824
Move some retired articles to the proper folder.
=> move retired articles

content/rackspace-email/view-and-read-rackspace-email-headers.md
=> COEDOCS-14-request

content/retired-articles/cloud-servers-how-to-articles-other-resources.md, content/retired-articles/getting-started-with-the-rackspace-mobile-application-and-managing-accounts.md
=> retire two articles

content/retired-articles/add-authorized-users-in-the-RackConnect-Management-Interface.md
=> retire rackconnect article

content/cloud-backup/install-or-update-the-cloud-backup-agent-on-linux.md
We are getting support calls for this, so it needs to be pushed as quickly as we can. Thanks so much!
=> set GPG keyring url to new address

content/cloud-servers/create-an-image-of-a-server-and-restore-a-server-from-a-saved-image.md
=> full audit create server image

content/cloud-backup/install-or-update-the-cloud-backup-agent-on-linux.md
Please push this through as soon as is convenient because it is likely to generate support calls for the same reason. Thanks so much!
=> CBU-212 make matching call to dpkg -i

content/cloud-servers/ssh-remote-host-identification-has-changed.md
=> Full Audit: SSH remote host identification

content/cloud-servers/cloud-servers-faq.md, content/retired-articles/live-migration-overview.md
infodev 1825
info in this article felt better suited to a FAQ rather than a standalone article
=> move live migration blurb to faq

content/cloud-servers/hidden-base-images.md
Adding Debian 7 as it has reached EOL
=> Adding Debian 7

content/cloud-servers/checking-for-a-security-compromise-rescue-mode-investigation.md
=> INFODEV-2091: Fix broken link

content/rackconnect/rackconnect-faq.md
=> Updating the FAQ for IPv6

content/dedicated-hosting/firewall-manager-v2-object-groups.md
=> Streamline object-group intro article

content/dedicated-hosting/firewall-manager-v2-object-groups.md
Keep the new ones I created for posterity.
=> Revert object group article changes

content/dedicated-hosting/firewall-manager-v2-object-groups.md
Reverts rackerlabs/rackspace-how-to#2698
=> Revert "Revert object group article changes"

content/rackspace-intelligence/getting-started-with-rackspace-intelligence-for-dedicated-accounts.md, content/retired-articles/viewing-and-creating-graphs-of-activity-in-rackspace-intelligence-for-dedicated-accounts.md
Remove link to retired article and move article to the retired folder
=> remove link to retired article

content/retired-articles/backup-your-mysql-database-with-phpmyadmin.md
pull off metadata to keep article from showing up in search results
=> remove metadata

content/cloud-servers/installing-an-ssl-certificate-on-apache.md
Apply changes from my SME to the ssl article
=> update install ssl apache

content/dedicated-hosting/windows-spheres-of-support-for-dedicated-and-managed-ops.md, content/managed-operations/cloud-servers-with-managed-operations-support-for-windows.md
New high level Rackspace SoS reviewed by WindowsTC
=> Windows Spheres of Support for Dedicated and Managed Operations

content/general/support.md
Update to match support page on main rackspace page
=> full audit support page

content/cloud-files/cloud-files-upload-download-issues-troubleshooting.md
Article focused at non-tech savvy customers to assist with initial troubleshooting.
=> New Article: Cloud Files Upload/Download Issues Troubleshooting

content/cloud-backup-troubleshooting-on-windows-2012-servers.md
New Article: Cloud Backup Troubleshooting on Windows 2012 Servers
=> New Article: Cloud Backup Troubleshooting

content/cloud-servers/resize-standard-and-general-purpose-servers.md
Resize information, including BFV
=> More clear around resizing

content/general/RPC-mitigations-against-cpu-speculative-execution-vulnerabilities.md, content/general/firmware-microcode-mitigations-against-cpu-speculative-execution-vulnerabilities.md, content/general/linux-os-mitigations-against-cpu-speculative-execution-vulnerabilities.md, content/general/rackspace-public-cloud-os-mitigations-against-cpu-speculative-execution-vulnerabilities.md, content/general/vmware-os-mitigations-against-cpu-speculative-execution-vulnerabilities.md, content/general/windows-os-mitigations-against-cpu-speculative-execution-vulnerabilities.md
add update links and intro
JIRA 2310
=> update CPU vulnerabilities child pages

content/cloud-backup/install-or-update-the-cloud-backup-agent-on-linux.md, content/cloud-backup/update-the-rackspace-cloud-backup-agent.md
We only support yum for RedHat-compatible systems.
=> DNF on Fedora not supported

content/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops.md
The SME has signed off on this change.
=> removed unsupported language from note in mail server section

content/general/change-to-new-primary-contact.md
Add self-service option for MyRackspace portal
JIRA 2308
=> update primary name change article

content/rackspace-email/rackspace-email-and-hosted-exchange-settings.md
At request of Technical Product Manager Mike Spaits, removed references to alternate/insecure client settings (endpoints/ports) due to upcoming product changes.
=> Insecure endpoint removal

content/managed-operations/cloud-server-configuration-options.md
=> full audit managed ops server config

content/cloud-networks/cloud-networks-faq.md
about outbound security groups.
=> Update link to community post

content/cloud-servers/shut-down-a-server.md
=> add experiment article

content/cloud-servers/cloud-backup-basic-troubleshooting-on-linux-servers.md
New article created to assist less technical customers with initial troubleshooting of Cloud Backups on their Cloud Server.
=> New Article: Cloud Backup - Basic troubleshooting on Linux Servers

content/cloud-servers/delete-a-server.md
=> full audit delete server

content/cloud-dns/como-modifico-meus-arquivos-de-hosts.md
=> Audit Portuguese version of this article.

content/retired-articles/manually-configure-outlook-2013-for-email-hosted-on-exchange-2007.md
=> retire exchange 2007 article

content/exchange/manually-configure-outlook-2013-for-email-hosted-on-exchange-2013.md
=> push small change

content/cloud-databases/managing-backups-for-cloud-databases.md
=> full audit database backups

content/managed-operations/gogrid-eol-faq.md
=> update gogrid faq

content/cloud-servers/mysql-connect-to-your-database-remotely.md
=> Jellyfish and grammatical edits: INFODEV-2516

content/cloud-servers/mysql-resetting-a-lost-mysql-root-password.md
=> add jellyfish links

content/cloud-dns/nslookup-checking-dns-records-on-windows.md
Will do a full audit via a separate PR.
=> Add Jellyfish link: infodev-2400

content/rackspace-email-archiving/index.md
=> Add how-to to link

content/cloud-dns/modify-your-hosts-file.md
Update wording and add product links
=> Update intro with Jellyfish recommendations

content/cloud-load-balancers/cloud-load-balancers-faq.md, content/cloud-load-balancers/configure-a-health-monitor-in-cloud-load-balancers.md, content/cloud-load-balancers/configure-a-load-balancer.md, content/cloud-load-balancers/content-caching-for-cloud-load-balancers.md, content/cloud-load-balancers/load-balancing-internal-ips-in-the-same-region.md, content/cloud-load-balancers/pointing-domains-to-load-balancers.md, content/cloud-load-balancers/prevent-server-overload-with-cloud-load-balancers.md, content/cloud-load-balancers/products-i-can-load-balance.md, content/cloud-load-balancers/using-the-rackspace-network-effectively.md
@cyrichardson Please review - ready to go.
=> Update control panel links and info for Cloud Load Balancers: INFODEV-2693

content/exchange/add-an-activesync-or-bes-license.md, content/exchange/cloud-office-control-panel-overview.md, content/general/billing-services-overview.md, content/general/change-account-company-name.md, content/general/change-account-information.md
=> cp URL fix 1

content/general/change-account-information.md, content/general/comparison-of-dedicated-and-cloud-hosting.md, content/general/linux-os-mitigations-against-cpu-speculative-execution-vulnerabilities.md, content/managed-operations/sitecore-cloud-portals-and-account-management.md, content/office-365/office-365-faq.md, content/rackconnect/access-the-rackconnect-management-interface.md, content/rackconnect/associate-a-cloud-account-with-rackconnect-v30.md
=> fix myrack urls 1

content/rackconnect/managing-rackconnect-v20-network-policies.md, content/rackconnect/rackconnect-faq.md, content/rackconnect/rackconnect-v20-automation-features-faq.md, content/rackconnect/rackconnect-v20-best-practices.md, content/rackconnect/rackconnect-v20.md, content/rackconnect/rackconnect-v30-limitations.md, content/rackconnect/rackconnect-v30-requirements.md, content/rackconnect/the-rackconnect-v20-api.md
=> Myrack fixes 2

content/rackspace-email/cloud-office-quick-start-for-uk-customers.md, content/rackspace-email/rackspace-directory-sync-install-and-configure.md, content/rackspace-email/rackspace-email-control-panel-overview.md, content/rackspace-email/upgrade-email-hosting-cloud-office-control-panel.md, content/rackspace-intelligence/log-in-to-rackspace-intelligence-for-dedicated-accounts.md
=> final batch of myrack fixes

content/cloud-servers/dovecot-installation-and-configuration-on-centos.md
Dovecot and Postfix are open source; I haven't found any reference to registered trademarks for these.
=> Apply peer edits to Dovecot article audit: infodev-1595

content/cloud-servers/manually-enable-auto-updates-on-rhel-and-centos-public-cloud-servers.md
add manually enable automatic updates for RHEL and CentOS
JIRA 2720
=> Rhel centos exp

content/cloud-servers/checking-for-a-security-compromise-backdoors-and-intruders.md
add lsof clarification
JIRA 2367
=> full audit security backdoors and intruders

content/cloud-servers/connecting-to-a-server-using-ssh-on-linux-or-mac-os.md
=> full audit

content/index.md, products.csv
=> add backend stuff for rackspace-pdr

content/rackspace-email/export-email-address-data-from-outlook-2016-for-windows.md
Fixed a typing error. Replaced "Ssave" with "Save".
=> Fixed a typing error.

content/rackspace-email/rackspace-email-faq.md, content/retired-articles/tls-ssl-encryption-cloud-office.md
=> move ssl info to co faq

content/rackspace-email/rackspace-directory-sync-install-and-configure.md
=> full audit rackspace directory sync

content/rackspace-email/password-management-and-best-practices.md
Fixing link to the spoofing article
=> fix wrong link

content/cloud-servers/getting-fanatical-support-7-live-chat.md, content/cloud-servers/permissions-matrix-for-role-based-access-control-rbac.md, content/general/getting-started-with-role-based-access-control-rbac.md, content/rackspace-email/cloud-office-migrations-faq.md, content/rackspace-email/delete-a-rackspace-email-mailbox.md, content/rackspace-monitoring/introducing-rackspace-monitoring-on-mobile-devices.md
Removing link to an article that doesn't exist
=> remove dead link

content/rackspace-email/renaming-a-rackspace-email-address-overview.md, content/rackspace-pdr/index.md, content/rackspace-pdr/rackspace-pdr-agent-compatibility.md, content/rackspace-pdr/rackspace-pdr-aws.md, content/rackspace-pdr/rackspace-pdr-azure.md, content/rackspace-pdr/rackspace-pdr-dedicated-servers.md, content/rackspace-pdr/rackspace-pdr-gcp.md
=> fix link issues

content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows.md, content/cloud-block-storage/detach-and-delete-cloud-block-storage-volumes.md, content/cloud-servers/checking-for-a-security-compromise-backdoors-and-intruders.md, content/cloud-servers/cloud-servers-faq.md, content/cloud-servers/common-windows-issues-key-management-server-activation.md, content/cloud-servers/index.md, content/cloud-servers/learn-more-about-cloud-servers.md, content/cloud-servers/resize-standard-and-general-purpose-servers.md, content/cloud-servers/resize-up-compute-and-memory-servers.md, content/dedicated-hosting/delete-an-object-group-with-firewall-manager-v2.md, content/dedicated-hosting/modify-an-object-group-with-firewall-manager-v2.md, content/dedicated-hosting/view-an-object-group-with-firewall-manager-v2.md, content/rackspace-email-archiving/log-in-to-the-archive-manager.md, content/rackspace-email/configure-a-renamed-email-address-in-apple-mail.md, content/rackspace-email/prepare-pop-imap-exchange-mail-servers-for-migration.md
=> fixing broken links

content/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops.md
=> update to match wiki changes

content/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops.md
=> Removed EoL Debian 7 (Wheezy)

content/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops.md
Added Containers section, with just Docker
https://jira.rax.io/browse/LTC-115
=> LTC-115 SOS - Docker Support

content/cloud-servers/checking-listening-ports-with-netstat.md
=> remove old feedback link

content/cloud-servers/mysql-resetting-a-lost-mysql-root-password.md
changing password column to authentication_string
=> update password column in alter user command

content/cloud-servers/index.md
Snapshots and images are different things.  Updated the references to snapshots to images instead.  The pages that are linked are correct with image.
=> Change snapshot to image

content/cloud-backup/best-practices-for-cloud-backup.md
=> full audit cloud backup best practices

content/cloud-servers/mysql-connect-to-your-database-remotely.md
seeing how the script works in the article, per David's suggestion
=> testing jellyfish schema

content/cloud-servers/cloud-backup-basic-troubleshooting-on-linux-servers.md
fixing a few rogue metadata issues
=> fix metadata issues

content/rackspace-pdr/rackspace-pdr-gcp.md
found an extra permalink in the metadata
=> remove duplicate permalink

content/cloud-servers/mysql-connect-to-your-database-remotely.md
jellyfish provided an update to the schema
=> replace schema with updated version

content/cloud-servers/logging-in-with-an-ssh-private-key-on-linuxmac.md
I made the text editing of the file step 1. Is that OK?
Or should I duplicate the article exactly in the script or rewrite this article to show substeps for creating the file, @stephamon?
=> Add schema optimization script

content/exchange/manually-configure-android-devices-for-email-hosted-on-exchange-2013.md
=> add jellyfish schema

content/rackspace-email/export-email-address-data-from-outlook-2013-for-windows.md
Added a registered symbol to Outlook and updated verbiage to more concisely describe actions.
=> Infodev 3088

content/cloud-servers/logging-in-with-an-ssh-private-key-on-windows.md
Updated references that this is to connect to a Linux server, not a Windows server. This is still using a Windows client with PuTTY installed.
=> Correct that PuTTY is connecting to a Linux server

content/general/change-account-information.md
=> Try to fix numbered list: INFODEV-3096

content/cloud-dns/nslookup-checking-dns-records-on-windows.md
Forgot to update the audit date when I originally audited this article in October.
=> Add audit date to article from October

content/cloud-load-balancers/cloud-load-balancers-faq.md
Will replace link to Community after that post has been converted into a How-To article. Mallory Hernandez in Cloud ESC said they would add it to the list of posts to be converted, but I replied offering to do it today.
=> Audit Cloud LBs FAQ: INFODEV-3003

content/wordpress-security-best-practices-linux.md
Migrating articles from the community as the community will be decommissioned soon.
=> Create Wordpress Security Best Practices (Linux)

content/general/rackspace-cloud-bandwidth-charges.md
=> update audit date

content/retired-articles/setting-up-imap-or-pop-windows-mail.md
Article should be ported over to emailhelp.rackspace.com.
=> retired windows mail article

content/cloud-servers/use-iptables-with-centos-7.md
Repurposing articles from the community to support.rackspace.com
=> Using iptables with CentOS 7

content/rackspace-monitoring/mobile-alerts-from-rackspace-monitoring.md
and other outdated source of help (IRC). Renamed section from "Help and contact" to "Additional resources"
=> Remove feedback.rackspace link

content/cloud-servers/cloud-servers-faq.md, content/cloud-servers/connecting-to-a-server-using-ssh-on-linux-or-mac-os.md, content/cloud-servers/upgrade-citrix-tools-for-windows-servers.md, content/general/rackspace-billing-faq.md, content/rpc-vmware/index.md
=> remove community references

content/cloud-servers/set-up-two-factor-authentication-by-using-google-authenticator.md
…ge paragrah. Duplicates https://github.com/rackerlabs/rackspace-how-to/pull/3018.
=> Add community article on fresh branch: INFODEV-3178

content/cloud-servers/upgrade-apache-http-server-2.2-to-2.4-in-rhel-and-centos.md
…s https://github.com/rackerlabs/rackspace-how-to/pull/3027/files
=> Add community article on fresh branch to break up large para: INFODEV-3231

content/cloud-servers/investigating-compromised-servers.md
Migrating article from the community to the knowledge center.  This article is very comprehensive and the two articles found currently in the knowledge center focus on specific issues.
=> Create Investigating Compromised Servers

content/cloud-images/cloud-image-creation-format-and-process.md, content/cloud-images/understanding-the-cloud-imaging-process.md
=> Community Cloud Imaging

content/cloud-servers/ensure-servers-reboot-successfully.md
=> Add community article on reboots: INFODEV-3256

content/cloud-servers/adding-disk-space-after-resizing-a-windows-server-2012-cloud-server.md
Previously it was written C:\\ so I have removed a slash so it reads C:\
=> Removed additional \

content/cloud-servers/install-ansible-playbook-for-cloud-monitoring.md
=> Add community article about Ansible: INFODEV-3283

content/cloud-servers/adding-disk-space-after-resizing-a-windows-server-2012-cloud-server.md
Article has been reviewed by SME. Ready for editor review @cyrichardson :)
=> INFODEV-1589

style-guidelines.md
Fixed broken link in the style guide.
=> INFODEV-3425

content/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops.md
Ubuntu 18.04 LTS for Dell and VMWare Platforms
=> Update Linux SoS with Ubuntu 18.04 LTS

content/cloud-servers/multi-factor-authentication-from-the-myrackspace-portal.md, content/exchange/add-multiple-contacts-to-exchange.md, content/exchange/clear-keychain-access-for-mac.md, content/office-365/add-an-office-365-license.md, content/office-365/set-up-office-365.md, content/rackspace-email/adding-a-rackspace-email-group-list.md, content/rackspace-email/adding-an-alias-with-rackspace-email.md, content/rackspace-email/edit-dns-in-the-cloud-office-control-panel.md, content/rackspace-email/enable-or-disable-two-factor-authentication-for-administrators.md, content/rackspace-email/rackspace-directory-sync-install-and-configure.md, content/rackspace-email/set-up-dns-records-for-cloud-office-email.md, content/retired-articles/upgrade-email-hosting-cloud-office-control-panel.md
of Cloud Office control panel to Cloud Office Control Panel
=> Change all occurrences 

content/cloud-servers/generate-a-csr.md
Got an email from a Racker who kindly pointed out these errors.
=> fix typo and wrong instruction

content/cloud-dns/modify-your-hosts-file.md, content/cloud-servers/mysql-connect-to-your-database-remotely.md, content/cloud-servers/mysql-resetting-a-lost-mysql-root-password.md, content/cloud-servers/troubleshoot-a-downed-linux-cloud-server.md
Update with new schema provided by Daniel & Co.
=> update article schema

content/general/rackspace-billing-faq.md
=> remove obsolete info

content/cloud-block-storage/cloud-block-storage-overview.md, content/cloud-block-storage/index.md, content/cloud-servers/preparing-data-disks-on-linux-cloud-servers.md, content/retired-articles/moving-a-software-raid-cloud-block-storage-volume-from-one-cloud-server-to-another.md
retire article, remove a couple of links, and edit another article.
=> raid cleanup

content/rackconnect/accessing-rackconnect-cloud-servers.md, content/rackconnect/associate-a-cloud-account-with-rackconnect-v30.md, content/rackconnect/cloud-orchestration-support-for-rackconnect-v30.md, content/rackconnect/comparing-rackconnect-v30-and-rackconnect-v20.md, content/rackconnect/getting-rackconnect-support.md, content/rackconnect/getting-started-with-the-rackconnect-v30-api.md, content/rackconnect/introducing-rackconnect-v20.md, content/rackconnect/introducing-rackconnect-v30.md, content/rackconnect/managing-rackconnect-v20-network-policies.md, content/rackconnect/new-features-available-in-rackconnect-v30.md, content/rackconnect/rackconnect-key-terms.md, content/rackconnect/rackconnect-v20-requirements.md, content/rackconnect/rackconnect-v20.md, content/rackconnect/rackconnect-v30-limitations.md, content/rackconnect/rackconnect-v30-requirements.md, content/rackconnect/using-cloud-load-balancers-with-rackconnect.md, content/rackconnect/using-onmetal-cloud-servers-with-rackconnect-v20.md, content/retired-articles/rackspace-cloud-essentials-rescue-mode-on-windows-cloud-servers-behaviors.md
I removed instructions from all articles that did not meet style guide specifications.
=> INFODEV-3631 remove instructions to contact support

content/cloud-backup/index.md
Fix link for renamed permalink
=> fix outdated link on index page

content/FAWS/using-putty-to-access-private-instances.md, content/retired-articles/cloud-servers-with-managed-operations-support-for-linux.md, content/retired-articles/getting-started-with-the-rackspace-mobile-application-and-managing-accounts.md, content/retired-articles/rackspace-private-cloud-spheres-of-support.md, content/retired-articles/sharepoint/index.md, content/rpc-microsoft/architecture-requirements-for-rackspace-private-cloud-powered-by-microsoft.md, content/rpc-microsoft/rpc-microsoft-faq.md, content/rpc-openstack/rpc-openstack-faq.md
And some movement toFanatical Experience
=> Batch 2 Change or removal of Fanatical Support and some movement to

content/cloud-servers/troubleshoot-windows-server-boot-failure-after-exiting-rescue-mode.md
=> add community article

content/cloud-servers/install-auter-on-centos6.md
Added support for Auter to the Lynis project and noticed the small typo.
=> Fixed typo in name

content/managed-operations/cloud-server-configuration-options.md
Don't release this doc update until the gateway config is in production. I will send you more details in an internal email.
=> Added gateway build_config option

content/index.md
=> swap rms and private cloud

content/index.md
Also moving Managed Operations to the top
=> move managed ops under rms

content/rackspace-email-archiving/import-and-export-archived-data.md
As requested by John in https://jira.rax.io/browse/INFODEV-3889
=> Update estimated completion times

content/dedicated-hosting/add-new-vpn-user-myrackspace-portal.md
=> Update control panel login instructions

content/dedicated-hosting/firewall-manager-v2-access-list-theory-and-best-practices.md
per Trevor Beck and Angela Howell
=> add best practice

content/dedicated-hosting/delete-an-object-group-with-firewall-manager-v2.md, content/dedicated-hosting/modify-an-object-group-with-firewall-manager-v2.md, content/dedicated-hosting/view-an-object-group-with-firewall-manager-v2.md
=> update cp instructions

content/index.md
merge after https://github.com/rackerlabs/nexus-control/pull/1048
=> change pdr logo to castle

content/contribution-class/contribution-class-exercise.md
Added responses to questions from Hiten.
=> Add responses to questions from Hiten

content/cloud-servers/permissions-matrix-for-role-based-access-control-rbac.md
https://developer.rackspace.com/docs/metrics/v2/
=> Added missing Cloud Metrics roles

content/exchange/public-folder-permissions-for-exchange-2007-and-2010.md
=> fixed broken link

content/cloud-servers/configuring-basic-security.md
=> full audit on configuring basic security

content/cloud-networks/index.md
Product is already at soft-launch, will be announced via blog post and portal within the next month
=> added fortigate section

content/cloud-dns/about-ttl-best-practices.md
=> Add instructions to change the TTL

content/cloud-servers/hidden-base-images.md
Added missing Debian 8 Image UUIDs
=> Added missing Debian 8 Image UUIDs

content/cloud-networks/using-security-groups.md
=> add security groups article

content/account-management/support-pin-faq.md
@cyrichardson can I get your eyes on this when you have a chance please?
=> Infodev 4086

content/cloud-servers/installing-python-novaclient-on-linux-and-mac-os.md
Openstack client is the latest from Openstack, and it's much simpler to use overall.
=> replaced obsolete info on RS novaclient

content/cloud-dns/changing-dns-settings-on-linux.md, content/cloud-dns/modify-your-hosts-file.md, content/cloud-servers/configuring-mysql-server-on-ubuntu.md, content/cloud-servers/installing-mysql-server-on-ubuntu.md, content/cloud-servers/mysql-resetting-a-lost-mysql-root-password.md
=> Add links in articles

content/retired-articles/creating-an-ubuntu-1310-image-for-the-rackspace-open-cloud.md
=> retire ubuntu 13 image article

content/account-management/support-pin-management.md
removed warning per Kristen Frankel
=> removed warning

content/cloud-servers/generate-a-csr.md
the generator no longer exists.  Instead, customers should submit a ticket request.
=> removed CSR generator

content/rackspace-email-archiving/create-an-email-archive-login-message.md
Reverts rackerlabs/rackspace-how-to#3351
=> Revert "Infodev 4556 - full audit"

content/account-management/change-the-primary-contact-on-a-cloud-office-account.md
Howdy @stephamon! Would you mind editing when you have a chance please?
Thanks!
=> New article Cloud Office Primary Contact change

content/rackspace-email/adding-an-alias-with-rackspace-email.md
to force a build so I can publish
=> dummy change

content/cloud-servers/installing-mysql-server-on-ubuntu.md
Created a Debian 9 server and verified the commands/instructions are correct.
=> Updates for Debian 9 Behavior

content/cloud-servers/migracion-de-nube-a-nube.md
=> add spanish version of cloud to cloud migration

content/cloud-servers/are-cloud-servers-pci-dss-compliant.md
JIRA 4569
Confirmed with SME that the content is still correct.
=> add audit date for up to date article

content/index.md
Made this change per the request of @ReneeRendon
=> Changed "Cloud Hosting" tab to "Cloud Services"

content/retired-articles/basic-cloud-server-use-scenarios.md
=> retire cloud server use scenarios

content/index.md
@stephamon would you mind taking a quick look at this for approval? Gracias :D
=> change getting started variable

content/getting-started/getting-started-with-public-cloud.md
For links that are complete sentences.
=> Add periods

content/retired-articles/email-migration-from-google.md
retire migrate email from google article
=> retire article

content/retired-articles/hosted-microsoft-lync-at-rackspace-deployment-guide.md
=> retire hosted lync article

content/index.md
This PR add a button under the Getting Started tab on support.rackspace.com/how-to/ that is labeled Getting Started with Rackspace Hosted Email. This PR can be validated. However, the styling for the button will come from another PR.
=> added getting started hosted email button

content/rackspace-pdr/rackspace-pdr-agent-compatibility.md
so spaces in published article is better
=> Changed to use headings rather than bold

content/cloud-servers/nova-agent-unix-and-rackspace-agent-windows.md
Makes this a bit more applicable for public-facing article
=> Minor changes.

content/rackconnect/access-the-rackconnect-management-interface.md, content/rackconnect/accessing-rackconnect-cloud-servers.md, content/rackconnect/associate-a-cloud-account-with-rackconnect-v30.md, content/rackconnect/cloud-orchestration-support-for-rackconnect-v30.md
add audit date and minor edits
JIRA 4692
=> RackConnect add audit dates part 1

content/rackconnect/how-to-prevent-rackconnect-from-overwriting-custom-iptables-rules-on-linux-cloud-servers.md, content/rackconnect/how-to-programmatically-determine-the-rackconnect-v20-automation-status-of-your-cloud.md, content/rackconnect/multiple-ssl-certificates-on-a-single-rackconnected-cloud-server-pat.md, content/rackconnect/new-features-available-in-rackconnect-v30.md, content/rackconnect/rackconnect-auto-nat-feature.md
=> rackconnect audit dates part 3

content/cloud-images/cloud-images-faq.md
ORD endpoints are now exposed on all US accounts.
=> Removed outdated info about ORD

content/cloud-dns/create-a-dkim-txt-record.md
=> org changes and minor edits

content/cloud-databases/enabling-the-root-user-on-cloud-databases.md, content/cloud-files/set-up-cloud-files-and-acls.md, content/cloud-images/preparing-an-image-for-import-into-the-rackspace-opencloud.md, content/cloud-servers/cloud-feeds-overview.md, content/cloud-servers/create-an-image-of-a-server-and-restore-a-server-from-a-saved-image.md, content/cloud-servers/installing-python-novaclient-on-linux-and-mac-os.md, content/cloud-servers/installing-python-novaclient-on-windows.md, content/cloud-servers/next-generation-cloud-servers-sample-code.md, content/rackspace-auto-scale/rackspace-auto-scale-tips-and-how-tos.md, content/retired-articles/configure-cloud-feeds-archiving-in-the-cloud-control-panel.md, content/retired-articles/detailed-permissions-matrix-for-cloud-big-data.md, content/retired-articles/sdks-for-java-ruby-python-nodejs-php-and-microsoftnet.md
replaced all instances of http with https for major Rackspace domain names
=> Http to https

content/cloud-servers/checking-system-load-on-linux.md
This was brought up by a Support Tech.  Instead of creating a brand new page for just the "free" command, it fit perfectly on this page.
=> Add "free" command

content/skype-for-business/hosted-microsoft-lync-at-rackspace-deployment-guide.md
Adding the deployment guide back since Skype for Business replaced Lync and this is still relevant.
=> Add Skype for Business Deployment Guide

content/general/ord1-cr5-cr8-data-center-consolidation-faq.md
=> two updates

content/cloud-servers/disable_http_compression_in_apache.md
https://jira.rax.io/browse/INFODEV-4762?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel
=> Disable apache

content/cloud-servers/connect-to-your-onmetal-server-through-cloud-init.md
SM made a minor change to code and I updated last modified date
=> update modify date

content/rackspace-email-archiving/early-adopters-add-and-edit-archive-users-in-cloud-office.md
Change created date from 2015-05-18 to 2019-11-8
Change created by from Beau Bailey to Joe Brooks
=> Change created date and created by

content/cloud-servers/elliptic-curve-operations.md
=> Add OpenSSL and Elliptic Curve operations

content/rackspace-pdr/rackspace-pdr-agent-compatibility.md
Hi team,
Just updated the newly released kernels by Crowdstrike
Thanks
Shampa
RMS-PDR
=> Updated Kernel list

content/cloud-servers/provided-host-name-not-valid.md
=> Add article to troubleshoot error provided-host-name-not-valid

content/cloud-servers/migrate-to-rackspace-from-another-hosting-provider.md
mainly sourced from my own article here: https://support.rackspace.com/how-to/migrate-gogrid-cloud-servers-to-rackspace-cloud/
=> replace rsync with InstanceSync

content/retired-articles/creating-a-centos-65-image-for-the-rackspace-open-cloud.md, content/retired-articles/email-access-options-during-an-email-migration.md, content/retired-articles/email-sorting-issues-on-ios-and-android-after-an-email-migration.md, content/retired-articles/migrating-your-drupal-database-to-cloud-servers.md, content/retired-articles/set-an-email-catch-all-address-in-the-cloud-office-control-panel.md, content/retired-articles/test-and-send-mail-using-php.md, content/skype-for-business/hosted-microsoft-lync-at-rackspace-deployment-guide.md
fixing meta issues that I found when getting metrics
=> fixing some retired article issues

content/rackconnect/cloud-server-images-for-use-with-rackconnect-v20.md, content/rackconnect/comparing-rackconnect-v30-and-rackconnect-v20.md, content/rackconnect/rackconnect-faq.md, content/rackconnect/rackconnect-key-terms.md, content/rackconnect/rackconnect-network-device-comparison.md, content/rackconnect/rackconnect-power-users-guide.md, content/rackconnect/rackconnect-v20-automation-features-faq.md, content/rackconnect/rackconnect-v20-best-practices.md, content/rackconnect/rackconnect-v20-compatibility-with-cloud-servers-images.md, content/rackconnect/rackconnect-v20-compatibility.md, content/rackconnect/rackconnect-v20-operational-limits.md, content/rackconnect/rackconnect-v20-requirements.md, content/rackconnect/rackconnect-v20.md, content/rackconnect/rackconnect-v30-cloud-server-image-compatibility.md, content/rackconnect/rackconnect-v30-compatibility.md, content/rackconnect/rackconnect-v30-limitations.md, content/rackconnect/rackconnect-v30-requirements.md, content/rackconnect/rackconnect-v30-retained-public-ip-addresses.md, content/rackconnect/rackconnect-v30-upgrade-information.md, content/rackconnect/reassign-a-cloud-network-ip-address-to-a-rackconnect-v3-cloud-server.md, content/rackconnect/the-rackconnect-v20-api.md, content/rackconnect/using-cloud-load-balancers-with-rackconnect.md, content/rackconnect/using-dedicated-load-balancers-with-rackconnect-v20.md, content/rackconnect/using-dedicated-load-balancers-with-rackconnect-v30.md, content/rackconnect/using-onmetal-cloud-servers-with-rackconnect-v20.md
=> Rackconnect stuff

content/cloud-servers/nova-agent-unix-and-rackspace-agent-windows.md, content/cloud-servers/paypal-requires-tls-12.md, content/cloud-servers/post-migration-considerations-when-migrating-from-amazon-web-services.md, content/cloud-servers/quick-start-guide-create-your-first-website-on-cloud-servers.md, content/cloud-servers/set-up-apache-virtual-hosts-on-ubuntu.md, content/cloud-servers/set-up-two-factor-authentication-by-using-google-authenticator.md, content/rackspace-monitoring/install-ansible-playbook-for-cloud-monitoring.md
=> more waldo

content/index.md
revert test changes to dedicated tab
=> revert dedicated tab

content/index.md
This PR must be merged alongside https://github.com/rackerlabs/nexus-control/pull/1106/commits/0cc92ba3a4baf846bc5f551254a2c88555dacc64
=> added button

content/cloud-servers/install-mongrel-and-mongrel-clusters-on-the-ubuntu-operating-system.md, content/cloud-servers/setting-up-sftp-users-in-linux-based-systems.md
=> rename for waldo purposes

content/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation.md, content/index.md
=> Dedicated tab

content/cloud-images/preparing-an-image-for-import-into-the-rackspace-opencloud.md
Updated information on image import
=> improved image import page

content/cloud-servers/reset-the-root-password-from-rescue-mode.md
Adding a link to the rescue mode article as suggested by the SME.
=> add audit date and link to another article

content/cloud-servers/using-the-apache-2-buddy-script-for-performance-and-stability.md
Formatting changes only. 
Fixed some weird formatting in the Apache2Buddy output to ease readability in initial output and output that is above the informational piece in the "Review the results" section.
=> Fix script output formatting

content/cloud-servers/how-to-install-a-lamp-stack-on-rhel-6-based-distributions.md
Line 36- Format change to show one-liner like the other code style boxes.
=> Fix formatting for one-liner

content/cloud-servers/using-the-apache-2-buddy-script-for-performance-and-stability.md
@catlook Please review these changes to see if you agree with them. If you do, please merge.
=> Editorial changes

content/cloud-servers/how-to-install-a-lamp-stack-on-rhel-7-based-distributions.md
New document to assist customers with creating a LAMP stack on RHEL 7 based distros.
=> Create new document for LAMP on RHEL 7 Distros

content/account-management/os-billable-services.md
JIRA 5405
Convert wiki page to an article.
=> add new article os billable services

content/retired-articles/blackberry/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2010.md, content/retired-articles/rackspace-cloud-native-security/cloud-native-security.md
retiring on request of the native security PM
=> retire cloud native security article

content/office-365/set-up-office-365.md
=> InfoDev-5469-updated last modified date

content/cloud-block-storage/cloud-block-storage-faq.md
Found the config file for snapshot limits, changed snapshot limit section to reflect accordingly.
=> Update snapshot limts

content/cloud-servers/basic-cloud-server-security.md, content/cloud-servers/wordpress-security-best-practices-linux.md, content/rackspace-pdr/rackspace-pdr-overview.md
=> audit articles with sme feedback

content/cloud-servers/windows-server-security-best-practices.md
Updated recommended password strength to a longer password and added a note about Cloud Backup vs Cloud Server Images as not all servers can be imaged and images should not be considered a full backup solution.
=> Update Windows server security best practices

enable-services-in-linux.md
Was showing @reg on the support page instead of the registered symbol
=> Update @reg to &reg

content/cloud-servers/allow-web-traffic-in-ufw.md
Submitting document to assist customers in opening software firewall ports in UFW
=> Create allow web traffic in ufw

content/cloud-load-balancers/configure-SSL-certificates-on-cloud-load-balancers.md
Request to create a new document on how to add an SSL certificate to a Cloud Load Balancer.
=> Create new article for SSL certs on Cloud Load Balancers

content/cloud-load-balancers/configure-multiple-SSL-certificates-on-cloud-load-balancers.md
This article is to assist customers with the newly implemented feature in the Cloud portal that allows customers to update certificate mappings on their Cloud Load Balancers
=> Create new article for multiple certificates on CLB (SNI)

content/cloud-servers/configure-password-expiration-in-windows.md
The "true" should be where the "false" was.
=> Swap true and false

content/cloud-load-balancers/configure-SSL-certificates-on-cloud-load-balancers.md
Update link to point to related article
=> Update related link on CLB document.

content/cloud-load-balancers/configure-multiple-SSL-certificates-on-cloud-load-balancers.md
Updating the link to the related document. 
Related to #3620
=> Update dead link on CLB document

content/cloud-servers/build-your-application-on-the-rackspace-cloud.md
Just some minor some changes. Article was audited last week
=> additional sme feedback

content/cloud-servers/managing-password-policies.md, content/cloud-servers/reboot-a-server.md
JIRA 5012 & 5013
SME confirmed that the articles are still correct, so I've just done a few edits and added audit dates.
=> update articles with audit date

content/rackspace-monitoring/mobile-alerts-from-rackspace-monitoring.md
Stumbled across an article with product metadata that needs fixing
=> fix product metadata

content/cloud-backup/install-or-update-the-cloud-backup-agent-on-linux.md
Add "(Deprecated)" to the old version of the article to make them look more separate.
=> distinguish titles and fix URL

content/skype-for-business/set-up-dns-records-for-cloud-office-skype-for-business.md
A couple of the tables had an extra bar in one of the cells, causing some problems when published. Also adding an extra blank line to force more separation between tables.
=> remove extra bar from table row

content/rms-alert-logic/about-the-alert-logic-agent.md, content/rms-alert-logic/alert-logic-and-diffie-hellman.md, content/rms-alert-logic/alert-logic-faq.md, content/rms-alert-logic/all.md, content/rms-alert-logic/index.md, content/rms-alert-logic/log-source-best-practices.md
I was asked by Kayse Horton to review the material and update as needed. I have done so, and my changes in the fork.
=> Updated RMS Network Defense Language - 4-1-2020

content/index.md
add the alert logic service offering to the landing page
=> add alert logic to landing page

content/cloud-servers/nova-agent-unix-and-rackspace-agent-windows.md
Also, how to run servers without nova-agent
=> More details on how to install nova-agent

content/cloud-servers/shut-down-a-cloud-server.md
Per Jackie Campbell.  Might need new delete server article.  Might also need redirect.
=> Remove delete instructions

content/cloud-servers/basic-linux-user-management.md
Just a minor edit. While usermod -L and usermod -U work fine, I wanted to change the commands to the passwd equivalent so it makes more sense with the flow of the article.
=> Change commands for locking/unlocking

content/cloud-dns/create-a-reverse-dns-record.md
JIRA 5672
content is good, so just a minor edit
=> minor edits

content/general/hkg2-data-center-migration-customer-faq.md
=> Update per Tom Hallam

content/rackconnect/rackconnect-v30-upgrade-information.md
we no longer release new images for RCv2
=> Added note about image compatibility

content/office-365/create-and-access-shared-mailboxes-office-365.md, content/office-365/getting-started-with-office-365.md
JIRA 5952 & 5953
SME confirmed that the content is still good, so just adding the audit dates here
=> add audit dates

content/cloud-images/preparing-an-image-for-import-into-the-rackspace-opencloud.md
Full details and practical example
=> updated instructions for image import

content/dedicated-hosting/configure-and-troubleshoot-ntfs-permissions.md
The author confirmed that the content is still good. The article is very new, so the audit date was probably just forgotten.
JIRA 5951
=> add missing audit date

content/cloud-networks/vyatta-eol-faq.md
=> added Vyatta EOL doc

content/cloud-servers/reset-a-server-password.md
=> first commit

content/cloud-servers/create-and-configure-a-user-in-mssql.md, content/cloud-servers/creating-and-configuring-a-user-in-mssql.md
JIRA 6106
removing a note as per SME guidance and some minor edits
=> remove outdated note and some minor edits

content/cloud-servers/migrating-between-server-flavors.md
Missing audit_date, last_modified_by, and last_updated. Also the product_url was incorrect
=> fix metadata

content/dedicated-hosting/windows-spheres-of-support-for-dedicated-and-managed-ops.md
Add support for SQL 2019 after Launch on 3-Aug-20
=> Add SQL 2019 Support
